## Neuronale Netze

In [2]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import accuracy_score, f1_score
from sklearn.inspection import permutation_importance
from sklearn.model_selection import GridSearchCV
from tensorflow import keras
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization, Input
from keras.models import Sequential
from keras.optimizers import Adam


# Setze Zufallssamen
initial_seed = 42
np.random.seed(initial_seed)
tf.random.set_seed(initial_seed)

In [3]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [4]:
# Globales DataFrame zur Speicherung der Ergebnisse
log_results_df = pd.DataFrame(columns=["Durchlauf", "Modell", "Accuracy", "F1 Score"])

def log_model_performance(durchlauf_name: str, model_name: str, y_pred, y_test, seed: int):
    """
    Berechnet Accuracy und F1-Score anhand von y_test und y_pred und
    fügt die Ergebnisse dem globalen DataFrame results_df hinzu.

    Parameter:
      - durchlauf_name: Name des Durchlaufs (String)
      - model_name: Name des verwendeten Modells (String)
      - y_pred: Vorhersagen des Modells
      - y_test: Wahre Zielwerte

    Gibt zurück:
      - Das aktualisierte DataFrame mit den Spalten "Durchlauf", "Modell", "Accuracy" und "F1 Score"
    """
    global log_results_df
    # Berechnung der Metriken
    acc = accuracy_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    # Neuen Eintrag als DataFrame erstellen
    new_row = pd.DataFrame({
        "Durchlauf": [durchlauf_name],
        "Modell": [model_name],
        "Seed": [seed],
        "Accuracy": [acc],
        "F1 Score": [f1]
    })

    # Ergebnisse zum globalen DataFrame hinzufügen
    log_results_df = pd.concat([log_results_df, new_row], ignore_index=True)
    return log_results_df

In [5]:
# Initialisiere das globale DataFrame
log_results_df = pd.DataFrame(columns=["Durchlauf", "Modell", "Seed", "Layers", "Neurons", "Dropout Rate", "Batch Normalization", "Accuracy", "F1 Score"])

def log_model_performance2(durchlauf_name: str, model_name: str, y_pred, y_test,
                          seed: int = None, layers: int = None, neurons: int = None,
                          dropout_rate: float = None, batch_norm: bool = None):
    """
    Berechnet Accuracy und F1-Score anhand von y_test und y_pred und
    fügt die Ergebnisse dem globalen DataFrame log_results_df hinzu.

    Parameter:
      - durchlauf_name: Name des Durchlaufs (String)
      - model_name: Name des verwendeten Modells (String)
      - y_pred: Vorhersagen des Modells
      - y_test: Wahre Zielwerte
      - seed: Verwendeter Seed (optional)
      - layers: Anzahl der Schichten (optional)
      - neurons: Anzahl der Neuronen pro Schicht (optional)
      - dropout_rate: Dropout-Rate (optional)
      - batch_norm: Verwendung von Batch Normalization (optional)
      - accuracy: Berechnete Accuracy (optional)
      - f1_score: Berechneter F1-Score (optional)

    Gibt zurück:
      - Das aktualisierte DataFrame mit den Spalten "Durchlauf", "Modell", "Seed", "Layers", "Neurons", "Dropout Rate", "Batch Normalization", "Accuracy" und "F1 Score"
    """
    global log_results_df

    # Berechnung der Metriken, falls nicht bereits übergeben

    accuracy = accuracy_score(y_test, y_pred)

    f1 = f1_score(y_test, y_pred)

    # Neuen Eintrag als DataFrame erstellen
    new_row = pd.DataFrame({
        "Durchlauf": [durchlauf_name],
        "Modell": [model_name],
        "Seed": [seed if seed is not None else "NA"],
        "Layers": [layers if layers is not None else "NA"],
        "Neurons": [neurons if neurons is not None else "NA"],
        "Dropout Rate": [dropout_rate if dropout_rate is not None else "NA"],
        "Batch Normalization": [batch_norm if batch_norm is not None else "NA"],
        "Accuracy": [accuracy],
        "F1 Score": [f1]
    })

    # Ergebnisse zum globalen DataFrame hinzufügen
    log_results_df = pd.concat([log_results_df, new_row], ignore_index=True)
    return log_results_df

In [6]:
df_training_all_features = pd.read_parquet(
    "df_training_all_features.parquet"
)

def create_and_train_model(df, target_column, epochs=50, batch_size=10):
    # Daten aufbereiten
    categorical_cols = ["Sex", "Ctry", "Town", "Goal of Training",
                        "Preferred Training Daytime", "Subscription Type", "Synchronisation"]
    df = df.drop(columns=categorical_cols)
    X = df.drop(columns=[target_column])
    y = df[target_column]
    
    # Aufteilung in Trainings- und Testdaten
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    
    # Erstelle das Modell
    model = Sequential()
    model.add(Dense(32, activation='relu', input_shape=(X_train.shape[1],),
                kernel_initializer=tf.keras.initializers.GlorotUniform(seed=42)))
    model.add(Dense(1, activation='sigmoid',
                    kernel_initializer=tf.keras.initializers.GlorotUniform(seed=42)))

    
    # Kompilieren des Modells
    model.compile(optimizer=Adam(), loss='binary_crossentropy', metrics=['accuracy'])
    
    # Trainieren des Modells
    model.fit(X_train, y_train, epochs=epochs, batch_size=batch_size, validation_split=0.2, verbose=1)
    
    # Evaluiere das Modell
    loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
    print(f"Test accuracy: {accuracy}")
    
    # Vorhersagen
    y_pred = model.predict(X_test)
    y_pred_class = (y_pred > 0.5).astype(int)
    
    return accuracy, y_pred_class, y_test


# Beispielaufruf
accuracy, y_pred_class, y_test = create_and_train_model(df_training_all_features, target_column="User of latest model")
df_results = log_model_performance("Baseline", "Neuronales Netz 2-Schichten 50 Epochen batchsize 10", y_pred_class, y_test)
df_results

categorical_cols = ["Sex", "Ctry", "Town", "Goal of Training",
                    "Preferred Training Daytime", "Subscription Type", "Synchronisation"]
df = df_training_all_features.drop(columns=categorical_cols)  # Ersetze dies mit deiner Datei

# Wähle die Zielvariable und die Features
target_column = "User of latest model"
X = df.drop(columns=[target_column])
y = df[target_column]

# Aufteilung in Trainings- und Testdaten
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

def baseline_nn(durchlauf, layers, neurons, seed=None, dropout_rate=0.0, batch_norm=False, epochs=50, batch_size=10):
    """
    Erstellt und trainiert ein neuronales Netzwerk mit festgelegten Parametern.
    
    Parameter:
      - layers: Anzahl der Schichten
      - neurons: Anzahl der Neuronen pro Schicht
      - seed: Zufallssamen für reproduzierbare Ergebnisse (optional)
      - dropout_rate: Dropout-Rate (optional)
      - batch_norm: Verwendung von Batch Normalization (optional)
      - epochs: Anzahl der Trainings-Epochen (optional)
      - batch_size: Batch-Größe (optional)
      
    Gibt zurück:
      - y_pred_class: Vorhersagen des Modells (binär)
      - y_test: Wahre Zielwerte
      - accuracy: Test-Accuracy des Modells
      - exp_df: DataFrame mit den Experiment-Ergebnissen
    """
    global X_train, X_test, y_train, y_test  # Verwende globale Trainings- und Testdaten
    
    # Setze Zufallssamen, wenn angegeben
    if seed is not None:
        np.random.seed(seed)
        tf.random.set_seed(seed)
    
    # Erstelle das Modell
    model = Sequential()
    model.add(Input(shape=(X_train.shape[1],)))
    for _ in range(layers):
        model.add(Dense(neurons, activation='relu'))
        if batch_norm:
            model.add(BatchNormalization())
        if dropout_rate > 0:
            model.add(Dropout(dropout_rate))
    model.add(Dense(1, activation='sigmoid'))
    
    # Kompilieren des Modells
    model.compile(optimizer=Adam(), loss='binary_crossentropy', metrics=['accuracy'])
    
    # Trainieren des Modells
    model.fit(X_train, y_train, epochs=epochs, batch_size=batch_size, validation_split=0.2, verbose=1)
    
    # Evaluiere das Modell auf dem Testdatensatz
    loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
    
    # Vorhersagen auf dem Testdatensatz
    y_pred = model.predict(X_test)
    y_pred_class = (y_pred > 0.5).astype(int)  # Konvertiere die Vorhersagen in 0 oder 1

    f1 = f1_score(y_test, y_pred_class)
    
    # Speichere die Ergebnisse in einem DataFrame
    exp = [{
        "Durchlauf": durchlauf,
        "Seed": seed,
        "Layers": layers,
        "Neurons": neurons,
        "Dropout Rate": dropout_rate,
        "Batch Normalization": batch_norm,
        "Test Accuracy": accuracy,
        "F1-Score": f1
    }]
    exp_df = pd.DataFrame(exp)
    
    return y_pred_class, y_test, accuracy, exp_df

# Beispielaufruf
y_pred_class, y_test, accuracy, exp_df = baseline_nn("Neuronales Netz",layers=2, neurons=64, seed=42, dropout_rate=0, batch_norm=False, epochs=50, batch_size=10)

exp_df

In [ ]:
categorical_cols = ["Sex", "Ctry", "Town", "Goal of Training",
                    "Preferred Training Daytime", "Subscription Type", "Synchronisation"]
df = df_training_all_features.drop(columns=categorical_cols)  # Ersetze dies mit deiner Datei

# Wähle die Zielvariable und die Features
target_column = "User of latest model"
X = df.drop(columns=[target_column])
y = df[target_column]

# Aufteilung in Trainings- und Testdaten
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = Sequential()
model.add(Input(shape=(X_train.shape[1],)))
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

# Kompilieren des Modells
model.compile(optimizer=Adam(), loss='binary_crossentropy', metrics=['accuracy'])

# Trainieren des Modells
model.fit(X_train, y_train, epochs=50, batch_size=10, validation_split=0.2, verbose=0)

# Evaluiere das Modell auf dem Testdatensatz
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f"Test accuracy: {accuracy}")

# Vorhersagen auf dem Testdatensatz
y_pred = model.predict(X_test)
y_pred_class = (y_pred > 0.5).astype(int)  # Konvertiere die Vorhersagen in 0 oder 1

# Logge die Ergebnisse
df_results = log_model_performance("Baseline", "Neuronales Netz 2-Layers", y_pred_class, y_test)
df_results

Test accuracy: 0.5435897707939148
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step

<ipython-input-52-e05d3ced303f>:32: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  log_results_df = pd.concat([log_results_df, new_row], ignore_index=True)

                    Durchlauf                    Modell  Accuracy  F1 Score
0  Baseline 50-Epo, 10-BatchS  Neuronales Netz 2-Layers   0.54359  0.636735

In [7]:
categorical_cols = ["Sex", "Ctry", "Town", "Goal of Training",
                    "Preferred Training Daytime", "Subscription Type", "Synchronisation"]
df = df_training_all_features.drop(columns=categorical_cols)  # Ersetze dies mit deiner Datei

# Wähle die Zielvariable und die Features
target_column = "User of latest model"
X = df.drop(columns=[target_column])
y = df[target_column]

# Aufteilung in Trainings- und Testdaten
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Baseline-Modellierung
def create_model(deep_layers, neurons, seed=None, dropout_rate=0.0, batch_norm=False):
    if seed is None:
        seed = np.random.randint(1, 100)  # Generiere einen zufälligen Seed
        print(f"No seed provided. Using random seed: {seed}")

    # Setze die Zufallsgeneratoren
    np.random.seed(seed)
    tf.random.set_seed(seed)
    model = Sequential()
    model.add(Input(shape=(X_train.shape[1],)))
    for _ in range(deep_layers):
        model.add(Dense(neurons, activation='relu',kernel_initializer=tf.keras.initializers.GlorotUniform(seed=seed)))
        if batch_norm:
            model.add(BatchNormalization())
        if dropout_rate > 0:
            model.add(Dropout(dropout_rate))
    model.add(Dense(1, activation='sigmoid'))
    return model, seed

In [8]:
# Beispielaufruf der create_model-Funktion
deep_layers = 1  # Definiere die Anzahl der Schichten
neurons = 32     # Definiere die Anzahl der Neuronen
model, seed = create_model(deep_layers=deep_layers, neurons=neurons)


model.compile(optimizer=Adam(), loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=50, batch_size=10, validation_split=0.2, verbose=0)


loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f"Test accuracy: {accuracy}")


y_pred = model.predict(X_test)
y_pred_class = (y_pred > 0.5).astype(int)

# Logge die Ergebnisse
df_results = log_model_performance2(f"Baseline", f"Neuronales Netz", y_pred_class, y_test, seed, deep_layers, neurons)
df_results

No seed provided. Using random seed: 52
Test accuracy: 0.5435897707939148
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step

<ipython-input-5-2064eb4499b3>:49: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  log_results_df = pd.concat([log_results_df, new_row], ignore_index=True)

,Durchlauf,Modell,Seed,Layers,Neurons,Dropout Rate,Batch Normalization,Accuracy,F1 Score
0,Baseline,Neuronales Netz,52,1,32,NA,NA,0.54359,0.630705

In [9]:

# Beispielaufruf der create_model-Funktion
deep_layers = 2  # Definiere die Anzahl der Schichten
neurons = 32     # Definiere die Anzahl der Neuronen
model, seed = create_model(deep_layers=deep_layers, neurons=neurons, seed=initial_seed)


model.compile(optimizer=Adam(), loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=50, batch_size=10, validation_split=0.2, verbose=0)


loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f"Test accuracy: {accuracy}")


y_pred = model.predict(X_test)
y_pred_class = (y_pred > 0.5).astype(int)

# Logge die Ergebnisse
df_results = log_model_performance2(f"Baseline", f"Neuronales Netz", y_pred_class, y_test, seed, deep_layers, neurons)
df_results

Test accuracy: 0.6051282286643982
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step

,Durchlauf,Modell,Seed,Layers,Neurons,Dropout Rate,Batch Normalization,Accuracy,F1 Score
0,Baseline,Neuronales Netz,52,1,32,NA,NA,0.543590,0.630705
1,Baseline,Neuronales Netz,42,2,32,NA,NA,0.605128,0.222222

In [10]:
# Beispielaufruf der create_model-Funktion
deep_layers = 3  # Definiere die Anzahl der Schichten
neurons = 64     # Definiere die Anzahl der Neuronen
model, seed = create_model(deep_layers=deep_layers, neurons=neurons, seed=initial_seed)


model.compile(optimizer=Adam(), loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=100, batch_size=50, validation_split=0.2, verbose=0)


loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f"Test accuracy: {accuracy}")


y_pred = model.predict(X_test)
y_pred_class = (y_pred > 0.5).astype(int)

# Logge die Ergebnisse
df_results = log_model_performance2(f"100 Epo, 50 BatchS", f"Neuronales Netz", y_pred_class, y_test, seed, deep_layers, neurons)
df_results

WARNING:tensorflow:5 out of the last 15 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7e7387c83b00> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

Test accuracy: 0.6512820720672607
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step

,Durchlauf,Modell,Seed,Layers,Neurons,Dropout Rate,Batch Normalization,Accuracy,F1 Score
0,Baseline,Neuronales Netz,52,1,32,NA,NA,0.543590,0.630705
1,Baseline,Neuronales Netz,42,2,32,NA,NA,0.605128,0.222222
2,"100 Epo, 50 BatchS",Neuronales Netz,42,3,64,NA,NA,0.651282,0.433333

In [13]:
df = df_training_all_features#.drop(columns=categorical_cols)  # Ersetze dies mit deiner Datei

# Wähle die Zielvariable und die Features
target_column = "User of latest model"
X = df.drop(columns=[target_column])
y = df[target_column]



# One-Hot-Encoding für kategoriale Features
categorical_features = ["Sex", "Ctry", "Town", "Goal of Training", "Preferred Training Daytime", "Subscription Type", "Synchronisation"]
X = pd.get_dummies(X, columns=categorical_features, drop_first=True)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

deep_layers = 4  # Definiere die Anzahl der Schichten
neurons = 64     # Definiere die Anzahl der Neuronen
model, seed = create_model(deep_layers=deep_layers, neurons=neurons, seed)


model.compile(optimizer=Adam(), loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=100, batch_size=50, validation_split=0.2, verbose=0)


loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f"Test accuracy: {accuracy}")


y_pred = model.predict(X_test)
y_pred_class = (y_pred > 0.5).astype(int)

# Logge die Ergebnisse
df_results = log_model_performance2(f"OneHot-Encoding", f"Neuronales Netz", y_pred_class, y_test, seed, deep_layers, neurons)
df_results

No seed provided. Using random seed: 86
Test accuracy: 0.7897436022758484
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step

,Durchlauf,Modell,Seed,Layers,Neurons,Dropout Rate,Batch Normalization,Accuracy,F1 Score
0,Baseline,Neuronales Netz,52,1,32,NA,NA,0.543590,0.630705
1,Baseline,Neuronales Netz,42,2,32,NA,NA,0.605128,0.222222
2,"100 Epo, 50 BatchS",Neuronales Netz,42,3,64,NA,NA,0.651282,0.433333
3,OneHot-Encoding,Neuronales Netz,52,3,64,NA,NA,0.558974,0.641667
4,OneHot-Encoding,Neuronales Netz,29,3,64,NA,NA,0.733333,0.711111
5,OneHot-Encoding,Neuronales Netz,86,4,64,NA,NA,0.789744,0.721088

In [14]:
model.save('model_OHEnc_86.keras')

#seeds = [42, 21, 100, 123, 500, 789, 999]
seeds = np.random.randint(1, 1000, size=20).tolist()

# Speichere die Ergebnisse in einem DataFrame
results_seeds = []

for seed in seeds:
    # Setze Zufallssamen
    np.random.seed(seed)
    tf.random.set_seed(seed)

    # Erstelle das Modell
    model, seed = create_model(deep_layers=3, neurons=64, seed=seed)

    # Kompilieren des Modells
    model.compile(optimizer=Adam(), loss='binary_crossentropy', metrics=['accuracy'])

    # Trainieren des Modells
    #stop_callback = StopTrainingCallback()
    model.fit(X_train, y_train, epochs=100, batch_size=50, validation_split=0.2, verbose=0)

    # Evaluiere das Modell
    loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
    print(f"Seed {seed}: Test accuracy = {accuracy}")

    # Speichere die Ergebnisse
    results_seeds.append({"Seed": seed, "Test Accuracy": accuracy})

results_seeds = pd.DataFrame(results_seeds)
best_seed = int(results_seeds.loc[results_seeds['Test Accuracy'].idxmax()]['Seed'])
print(f"Best Seed in this random run and env: \n{best_seed}")

In [16]:
#seeds = [42, 21, 100, 123, 500, 789, 999]
seeds = np.random.randint(1, 1000, size=20).tolist()

# Speichere die Ergebnisse in einem DataFrame
results_seeds = []

for seed in seeds:
    # Setze Zufallssamen
    np.random.seed(seed)
    tf.random.set_seed(seed)

    # Erstelle das Modell
    model, seed = create_model(deep_layers=3, neurons=64, seed=seed)

    # Kompilieren des Modells
    model.compile(optimizer=Adam(), loss='binary_crossentropy', metrics=['accuracy'])

    # Trainieren des Modells
    #stop_callback = StopTrainingCallback()
    model.fit(X_train, y_train, epochs=100, batch_size=50, validation_split=0.2, verbose=0)

    # Evaluiere das Modell
    loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
    print(f"Seed {seed}: Test accuracy = {accuracy}")

    # Speichere die Ergebnisse
    results_seeds.append({"Seed": seed, "Test Accuracy": accuracy})

Seed 939: Test accuracy = 0.7333333492279053
Seed 754: Test accuracy = 0.656410276889801
Seed 858: Test accuracy = 0.5230769515037537
Seed 313: Test accuracy = 0.6717948913574219
Seed 502: Test accuracy = 0.6871795058250427
Seed 381: Test accuracy = 0.6871795058250427
Seed 207: Test accuracy = 0.6000000238418579
Seed 110: Test accuracy = 0.7179487347602844
Seed 577: Test accuracy = 0.7230769395828247
Seed 239: Test accuracy = 0.5487179756164551
Seed 994: Test accuracy = 0.7076923251152039
Seed 715: Test accuracy = 0.692307710647583
Seed 763: Test accuracy = 0.5538461804389954
Seed 709: Test accuracy = 0.5743589997291565
Seed 674: Test accuracy = 0.7230769395828247
Seed 890: Test accuracy = 0.6871795058250427
Seed 470: Test accuracy = 0.5692307949066162
Seed 78: Test accuracy = 0.7076923251152039
Seed 58: Test accuracy = 0.5589743852615356
Seed 125: Test accuracy = 0.6512820720672607

In [18]:
# Experimentiere mit verschiedenen Parametern
param_opt = []
seed = 86

deep_layers = [3, 4]
neurons = [64, 128]
dropout_rates = [0.0, 0.2,]
batch_norm_options = [True, False]


np.random.seed(seed)
tf.random.set_seed(seed)
for layer in deep_layers:
    for neuron in neurons:
        for dropout_rate in dropout_rates:
            for batch_norm in batch_norm_options:
                model, seed = create_model(seed=seed, deep_layers=layer, neurons=neuron, dropout_rate=dropout_rate, batch_norm=batch_norm)
                model.compile(optimizer=Adam(), loss='binary_crossentropy', metrics=['accuracy'])
                model.fit(X_train, y_train, epochs=100, batch_size=50, validation_split=0.2, verbose=0)
                loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
                param_opt = log_model_performance2(f"Ganzheitliche Optimierung", f"Neuronales Netz", y_pred_class, y_test, seed, layer, neuron, dropout_rate, batch_norm)


param_opt

,Durchlauf,Modell,Seed,Layers,Neurons,Dropout Rate,Batch Normalization,Accuracy,F1 Score
0,Baseline,Neuronales Netz,52,1,32,NA,NA,0.543590,0.630705
1,Baseline,Neuronales Netz,42,2,32,NA,NA,0.605128,0.222222
2,"100 Epo, 50 BatchS",Neuronales Netz,42,3,64,NA,NA,0.651282,0.433333
3,OneHot-Encoding,Neuronales Netz,52,3,64,NA,NA,0.558974,0.641667
4,OneHot-Encoding,Neuronales Netz,29,3,64,NA,NA,0.733333,0.711111
5,OneHot-Encoding,Neuronales Netz,86,4,64,NA,NA,0.789744,0.721088
6,Ganzheitliche Optimierung,Neuronales Netz,86,3,64,0.0,True,0.789744,0.721088
7,Ganzheitliche Optimierung,Neuronales Netz,86,3,64,0.0,False,0.789744,0.721088
8,Ganzheitliche Optimierung,Neuronales Netz,86,3,64,0.2,True,0.789744,0.721088
9,Ganzheitliche Optimierung,Neuronales Netz,86,3,64,0.2,False,0.789744,0.721088
10,Ganzheitliche Optimierung,Neuronales Netz,86,3,128,0.0,True,0.789744,0.721088
11,Ganzheitliche Optimierung,Neuronales Netz,86,3,128,0.0,False,0.789744,0.721088
12,Ganzheitliche Optimierung,Neuronales Netz,86,3,128,0.2,True,0.789744,0.721088
13,Ganzheitliche Optimierung,Neuronales Netz,86,3,128,0.2,False,0.789744,0.721088
14,Ganzheitliche Optimierung,Neuronales Netz,86,4,64,0.0,True,0.789744,0.721088
15,Ganzheitliche Optimierung,Neuronales Netz,86,4,64,0.0,False,0.789744,0.721088
16,Ganzheitliche Optimierung,Neuronales Netz,86,4,64,0.2,True,0.789744,0.721088
17,Ganzheitliche Optimierung,Neuronales Netz,86,4,64,0.2,False,0.789744,0.721088
18,Ganzheitliche Optimierung,Neuronales Netz,86,4,128,0.0,True,0.789744,0.721088
19,Ganzheitliche Optimierung,Neuronales Netz,86,4,128,0.0,False,0.789744,0.721088
20,Ganzheitliche Optimierung,Neuronales Netz,86,4,128,0.2,True,0.789744,0.721088
21,Ganzheitliche Optimierung,Neuronales Netz,86,4,128,0.2,False,0.789744,0.721088

In [22]:
deep_layers = 3  # Definiere die Anzahl der Schichten
neurons = 64     # Definiere die Anzahl der Neuronen
model, seed = create_model(deep_layers=deep_layers, neurons=neurons, seed=seed)

results_fit_param=[]

epochs_options = [50, 100, 200]
batch_size_options = [10, 32, 64, 128]

for epochs in epochs_options:
        for batch_size in batch_size_options:
            model.compile(optimizer=Adam(), loss='binary_crossentropy', metrics=['accuracy'])
            model.fit(X_train, y_train, epochs=epochs, batch_size=batch_size, validation_split=0.2, verbose=0)
            loss, accuracy = model.evaluate(X_test, y_test, verbose=0)

            loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
            y_pred = model.predict(X_test)
            y_pred_class = (y_pred > 0.5).astype(int)

            results_fit_param.append({
                "Seed": seed,
                "Epochs": epochs,
                "Batch Size": batch_size,
                "Test Accuracy": accuracy,
                "F1 Score": f1_score(y_test, y_pred_class)
            })
results_fit_param = pd.DataFrame(results_fit_param)
results_fit_param

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step

    Seed  Epochs  Batch Size  Test Accuracy  F1 Score
0     86      50          10       0.646154  0.666667
1     86      50          32       0.748718  0.631579
2     86      50          64       0.482051  0.613027
3     86      50         128       0.733333  0.617647
4     86     100          10       0.769231  0.701987
5     86     100          32       0.758974  0.728324
6     86     100          64       0.743590  0.657534
7     86     100         128       0.743590  0.647887
8     86     200          10       0.620513  0.339286
9     86     200          32       0.758974  0.680272
10    86     200          64       0.738462  0.653061
11    86     200         128       0.707692  0.595745

In [20]:
seed

86

In [24]:
deep_layers = 4  # Definiere die Anzahl der Schichten
neurons = 64     # Definiere die Anzahl der Neuronen
model, seed = create_model(deep_layers=deep_layers, neurons=neurons, seed=seed)


model.compile(optimizer=Adam(), loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=100, batch_size=50, validation_split=0.2, verbose=0)


loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f"Test accuracy: {accuracy}")


y_pred = model.predict(X_test)
y_pred_class = (y_pred > 0.5).astype(int)

# Logge die Ergebnisse
df_results = log_model_performance2(f"Seed Optimierung", f"Neuronales Netz", y_pred_class, y_test, seed, deep_layers, neurons)
df_results

Test accuracy: 0.764102578163147
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step

,Durchlauf,Modell,Seed,Layers,Neurons,Dropout Rate,Batch Normalization,Accuracy,F1 Score
0,Baseline,Neuronales Netz,52,1,32,NA,NA,0.543590,0.630705
1,Baseline,Neuronales Netz,42,2,32,NA,NA,0.605128,0.222222
2,"100 Epo, 50 BatchS",Neuronales Netz,42,3,64,NA,NA,0.651282,0.433333
3,OneHot-Encoding,Neuronales Netz,52,3,64,NA,NA,0.558974,0.641667
4,OneHot-Encoding,Neuronales Netz,29,3,64,NA,NA,0.733333,0.711111
5,OneHot-Encoding,Neuronales Netz,86,4,64,NA,NA,0.789744,0.721088
6,Ganzheitliche Optimierung,Neuronales Netz,86,3,64,0.0,True,0.789744,0.721088
7,Ganzheitliche Optimierung,Neuronales Netz,86,3,64,0.0,False,0.789744,0.721088
8,Ganzheitliche Optimierung,Neuronales Netz,86,3,64,0.2,True,0.789744,0.721088
9,Ganzheitliche Optimierung,Neuronales Netz,86,3,64,0.2,False,0.789744,0.721088
10,Ganzheitliche Optimierung,Neuronales Netz,86,3,128,0.0,True,0.789744,0.721088
11,Ganzheitliche Optimierung,Neuronales Netz,86,3,128,0.0,False,0.789744,0.721088
12,Ganzheitliche Optimierung,Neuronales Netz,86,3,128,0.2,True,0.789744,0.721088
13,Ganzheitliche Optimierung,Neuronales Netz,86,3,128,0.2,False,0.789744,0.721088
14,Ganzheitliche Optimierung,Neuronales Netz,86,4,64,0.0,True,0.789744,0.721088
15,Ganzheitliche Optimierung,Neuronales Netz,86,4,64,0.0,False,0.789744,0.721088
16,Ganzheitliche Optimierung,Neuronales Netz,86,4,64,0.2,True,0.789744,0.721088
17,Ganzheitliche Optimierung,Neuronales Netz,86,4,64,0.2,False,0.789744,0.721088
18,Ganzheitliche Optimierung,Neuronales Netz,86,4,128,0.0,True,0.789744,0.721088
19,Ganzheitliche Optimierung,Neuronales Netz,86,4,128,0.0,False,0.789744,0.721088
20,Ganzheitliche Optimierung,Neuronales Netz,86,4,128,0.2,True,0.789744,0.721088
21,Ganzheitliche Optimierung,Neuronales Netz,86,4,128,0.2,False,0.789744,0.721088
22,Seed Optimierung,Neuronales Netz,86,4,64,NA,NA,0.605128,0.222222
23,Seed Optimierung,Neuronales Netz,86,4,64,NA,NA,0.764103,0.712500

# Experimentiere mit verschiedenen Parametern
param_opt = []
seeds = np.random.randint(1, 1000, size=5).tolist()
deep_layers = [3, 4]
neurons = [64, 128]
dropout_rates = [0.0, 0.2]
batch_norm_options = [True, False]

for seed in seeds:
    np.random.seed(seed)
    tf.random.set_seed(seed)
    for layer in deep_layers:
        for neuron in neurons:
            for dropout_rate in dropout_rates:
                for batch_norm in batch_norm_options:
                    model, seed = create_model(seed=seed, deep_layers=layer, neurons=neuron, dropout_rate=dropout_rate, batch_norm=batch_norm)
                    model.compile(optimizer=Adam(), loss='binary_crossentropy', metrics=['accuracy'])
                    stop_callback = StopTrainingCallback()
                    model.fit(X_train, y_train, epochs=100, batch_size=50, validation_split=0.2, callbacks=[stop_callback], verbose=0)
                    loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
                    param_opt = log_model_performance2(f"Ganzheitliche Optimierung", f"Neuronales Netz", y_pred_class, y_test, seed, layer, neuron, dropout_rate, batch_norm)


param_opt

param_opt.loc[param_opt['Accuracy'].idxmax()]#'Seed']

# Test

In [ ]:
categorical_cols = ["Sex", "Ctry", "Town", "Goal of Training",
                    "Preferred Training Daytime", "Subscription Type", "Synchronisation"]
df = df_training_all_features.drop(columns=categorical_cols)  # Ersetze dies mit deiner Datei

# Wähle die Zielvariable und die Features
target_column = "User of latest model"
X = df.drop(columns=[target_column])
y = df[target_column]

# Aufteilung in Trainings- und Testdaten
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = Sequential()
model.add(Input(shape=(X_train.shape[1],)))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

# Kompilieren des Modells
model.compile(optimizer=Adam(), loss='binary_crossentropy', metrics=['accuracy'])

# Trainieren des Modells
model.fit(X_train, y_train, epochs=50, batch_size=10, validation_split=0.2, verbose=1)

# Evaluiere das Modell auf dem Testdatensatz
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f"Test accuracy: {accuracy}")

# Vorhersagen auf dem Testdatensatz
y_pred = model.predict(X_test)
y_pred_class = (y_pred > 0.5).astype(int)  # Konvertiere die Vorhersagen in 0 oder 1

# Logge die Ergebnisse
df_results = log_model_performance("Baseline 50-Epo, 10-BatchS", "Neuronales Netz 3-Layers", y_pred_class, y_test)
df_results

Epoch 1/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.5163 - loss: 43.9666 - val_accuracy: 0.5449 - val_loss: 4.8993
Epoch 2/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5523 - loss: 5.6177 - val_accuracy: 0.6346 - val_loss: 2.5015
Epoch 3/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6356 - loss: 2.5760 - val_accuracy: 0.6410 - val_loss: 1.4502
Epoch 4/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5869 - loss: 3.5971 - val_accuracy: 0.5513 - val_loss: 4.6849
Epoch 5/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5640 - loss: 4.2084 - val_accuracy: 0.5449 - val_loss: 3.7175
Epoch 6/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6310 - loss: 2.6727 - val_accuracy: 0.5962 - val_loss: 3.8977
Epoch 7/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5848 - loss: 3.9533 - val_accuracy: 0.6538 - val_loss: 2.4723
Epoch 8/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6084 - loss: 3.7738 - val_accuracy: 0.6282 - val_loss: 2.3213
Epoch 9/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6797 - loss: 2.1271 - val_accuracy: 0.6987 - val_loss: 1.8353
Epoch 10/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6389 - loss: 3.9042 - val_accuracy: 0.6410 - val_loss: 4.0604
Epoch 11/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6020 - loss: 5.8877 - val_accuracy: 0.6603 - val_loss: 2.1127
Epoch 12/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6510 - loss: 2.6231 - val_accuracy: 0.5513 - val_loss: 5.0817
Epoch 13/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6503 - loss: 4.4281 - val_accuracy: 0.5449 - val_loss: 6.1366
Epoch 14/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6020 - loss: 5.4756 - val_accuracy: 0.6538 - val_loss: 2.6363
Epoch 15/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7324 - loss: 2.1048 - val_accuracy: 0.5449 - val_loss: 11.6575
Epoch 16/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6263 - loss: 5.9157 - val_accuracy: 0.7500 - val_loss: 1.5244
Epoch 17/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6761 - loss: 2.5993 - val_accuracy: 0.5449 - val_loss: 9.4512
Epoch 18/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6448 - loss: 3.2357 - val_accuracy: 0.7179 - val_loss: 1.5527
Epoch 19/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6373 - loss: 2.5117 - val_accuracy: 0.6410 - val_loss: 2.0755
Epoch 20/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6051 - loss: 5.7720 - val_accuracy: 0.5321 - val_loss: 7.6920
Epoch 21/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6063 - loss: 8.1150 - val_accuracy: 0.5000 - val_loss: 11.9815
Epoch 22/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6179 - loss: 4.2763 - val_accuracy: 0.6026 - val_loss: 3.6590
Epoch 23/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6016 - loss: 4.5217 - val_accuracy: 0.5449 - val_loss: 21.7591
Epoch 24/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6426 - loss: 5.5643 - val_accuracy: 0.5513 - val_loss: 7.1109
Epoch 25/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6240 - loss: 5.3043 - val_accuracy: 0.5449 - val_loss: 9.4640
Epoch 26/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5969 - loss: 7.2777 - val_accuracy: 0.6731 - val_loss: 2.3483
Epoch 27/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6345 - loss: 4.6279 - val_accuracy: 0.7628 - val_loss: 1.8005
Epoch 28/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6843 - loss: 3.5941 - val_accuracy: 0.5897 - val_loss: 3.6694
Epoch 29/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5925 - loss: 5.7973 - val_accuracy: 0.7244 - val_loss: 1.8875
Epoch 30/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6734 - loss: 2.9069 - val_accuracy: 0.5449 - val_loss: 11.5237
Epoch 31/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6620 - loss: 5.1770 - val_accuracy: 0.7692 - val_loss: 1.7459
Epoch 32/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7514 - loss: 2.4405 - val_accuracy: 0.6859 - val_loss: 2.1921
Epoch 33/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7151 - loss: 1.8949 - val_accuracy: 0.7051 - val_loss: 1.5876
Epoch 34/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6940 - loss: 2.2436 - val_accuracy: 0.5513 - val_loss: 5.6477
Epoch 35/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5760 - loss: 4.4175 - val_accuracy: 0.7500 - val_loss: 1.5192
Epoch 36/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6769 - loss: 2.1644 - val_accuracy: 0.6603 - val_loss: 2.4154
Epoch 37/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6984 - loss: 2.0482 - val_accuracy: 0.5962 - val_loss: 2.9358
Epoch 38/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6004 - loss: 6.2505 - val_accuracy: 0.5449 - val_loss: 8.4663
Epoch 39/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6241 - loss: 4.3609 - val_accuracy: 0.7051 - val_loss: 1.7822
Epoch 40/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6802 - loss: 2.4246 - val_accuracy: 0.6154 - val_loss: 3.0264
Epoch 41/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7065 - loss: 2.2896 - val_accuracy: 0.5513 - val_loss: 4.0756
Epoch 42/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6530 - loss: 2.8611 - val_accuracy: 0.5641 - val_loss: 4.1897
Epoch 43/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6653 - loss: 3.1022 - val_accuracy: 0.5705 - val_loss: 3.7513
Epoch 44/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6991 - loss: 5.5476 - val_accuracy: 0.7051 - val_loss: 1.8837
Epoch 45/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6481 - loss: 3.7591 - val_accuracy: 0.6090 - val_loss: 5.0717
Epoch 46/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6067 - loss: 5.1574 - val_accuracy: 0.7051 - val_loss: 1.8633
Epoch 47/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6493 - loss: 3.3481 - val_accuracy: 0.4936 - val_loss: 6.9796
Epoch 48/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6631 - loss: 3.0763 - val_accuracy: 0.7500 - val_loss: 1.3958
Epoch 49/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7500 - loss: 1.3722 - val_accuracy: 0.6923 - val_loss: 1.7947
Epoch 50/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7067 - loss: 2.0745 - val_accuracy: 0.5962 - val_loss: 3.2101

WARNING:tensorflow:5 out of the last 15 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x78f9d3517c40> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

Test accuracy: 0.5692307949066162
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step

,Durchlauf,Modell,Accuracy,F1 Score
0,Baseline,Neuronales Netz 2-Schichten 50 Epochen batchsize 10,0.507692,0.625000
1,Baseline,Neuronales Netz 2-Schichten 50 Epochen batchsize 10,0.446154,0.600000
2,"Baseline 50-Epo, 10-BatchS",Neuronales Netz 2-Layers,0.697436,0.628931
3,"Baseline 50-Epo, 10-BatchS",Neuronales Netz 3-Layers,0.569231,0.142857

In [ ]:
categorical_cols = ["Sex", "Ctry", "Town", "Goal of Training",
                    "Preferred Training Daytime", "Subscription Type", "Synchronisation"]
df = df_training_all_features.drop(columns=categorical_cols)  # Ersetze dies mit deiner Datei

# Wähle die Zielvariable und die Features
target_column = "User of latest model"
X = df.drop(columns=[target_column])
y = df[target_column]

# Aufteilung in Trainings- und Testdaten
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = Sequential()
model.add(Input(shape=(X_train.shape[1],)))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

# Kompilieren des Modells
model.compile(optimizer=Adam(), loss='binary_crossentropy', metrics=['accuracy'])

# Trainieren des Modells
model.fit(X_train, y_train, epochs=100, batch_size=50, validation_split=0.2, verbose=1)

# Evaluiere das Modell auf dem Testdatensatz
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f"Test accuracy: {accuracy}")

# Vorhersagen auf dem Testdatensatz
y_pred = model.predict(X_test)
y_pred_class = (y_pred > 0.5).astype(int)  # Konvertiere die Vorhersagen in 0 oder 1

# Logge die Ergebnisse
df_results = log_model_performance("Baseline 100-Epo, 50-BatchS", "Neuronales Netz 3-Layers", y_pred_class, y_test)
df_results

In [ ]:
# Daten aufbereiten
categorical_cols = ["Sex", "Ctry", "Town", "Goal of Training",
                    "Preferred Training Daytime", "Subscription Type", "Synchronisation"]
df = df_training_all_features.drop(columns=categorical_cols)
target_column = "User of latest model"
X = df.drop(columns=[target_column])
y = df[target_column]

# Aufteilung in Trainings- und Testdaten
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Liste der Seeds
#seeds = [42, 21, 100, 123, 500, 789, 999]
seeds = np.random.randint(1, 10000, size=20).tolist()

# Speichere die Ergebnisse in einem DataFrame
results_seeds = []

for seed in seeds:
    # Setze Zufallssamen
    np.random.seed(seed)
    tf.random.set_seed(seed)

    # Erstelle das Modell
    model = Sequential()
    model.add(Input(shape=(X_train.shape[1],)))  # Verwende Input Layer
    model.add(Dense(64, activation='relu', kernel_initializer=tf.keras.initializers.GlorotUniform(seed=seed)))
    model.add(Dense(32, activation='relu', kernel_initializer=tf.keras.initializers.GlorotUniform(seed=seed)))
    model.add(Dense(1, activation='sigmoid', kernel_initializer=tf.keras.initializers.GlorotUniform(seed=seed)))

    # Kompilieren des Modells
    model.compile(optimizer=Adam(), loss='binary_crossentropy', metrics=['accuracy'])

    # Trainieren des Modells
    model.fit(X_train, y_train, epochs=100, batch_size=50, validation_split=0.2, verbose=0)

    # Evaluiere das Modell
    loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
    print(f"Seed {seed}: Test accuracy = {accuracy}")

    # Speichere die Ergebnisse
    results_seeds.append({"Seed": seed, "Test Accuracy": accuracy})

Seed 9137: Test accuracy = 0.728205144405365
Seed 6914: Test accuracy = 0.5948718190193176
Seed 5326: Test accuracy = 0.7128205299377441
Seed 9830: Test accuracy = 0.7128205299377441
Seed 5586: Test accuracy = 0.5230769515037537
Seed 9700: Test accuracy = 0.6051282286643982
Seed 7292: Test accuracy = 0.6820513010025024
Seed 7528: Test accuracy = 0.7179487347602844
Seed 5753: Test accuracy = 0.7230769395828247
Seed 1309: Test accuracy = 0.728205144405365
Seed 1253: Test accuracy = 0.5641025900840759
Seed 1204: Test accuracy = 0.7384615540504456
Seed 1443: Test accuracy = 0.6102564334869385
Seed 7182: Test accuracy = 0.6410256624221802
Seed 7655: Test accuracy = 0.6717948913574219
Seed 1444: Test accuracy = 0.7230769395828247
Seed 8234: Test accuracy = 0.7179487347602844
Seed 9333: Test accuracy = 0.7076923251152039
Seed 2692: Test accuracy = 0.5641025900840759
Seed 394: Test accuracy = 0.728205144405365

In [ ]:
results_seeds = pd.DataFrame(results_seeds)
best_seed = int(results_seeds.loc[results_seeds['Test Accuracy'].idxmax()]['Seed'])
print(f"Best Seed in this random run and env: \n{best_seed}")

Best Seed in this random run and env:
1204

In [ ]:
# Daten aufbereiten
categorical_cols = ["Sex", "Ctry", "Town", "Goal of Training",
                    "Preferred Training Daytime", "Subscription Type", "Synchronisation"]
df = df_training_all_features.drop(columns=categorical_cols)
target_column = "User of latest model"
X = df.drop(columns=[target_column])
y = df[target_column]

# Aufteilung in Trainings- und Testdaten
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Liste der Seeds
#seeds = [42, 21, 100, 123, 500, 789, 999]
seeds = np.random.randint(1, 10000, size=20).tolist()

# Speichere die Ergebnisse in einem DataFrame
results_seeds = []

for seed in seeds:
    # Setze Zufallssamen
    np.random.seed(seed)
    tf.random.set_seed(seed)

    # Erstelle das Modell
    model = Sequential()
    model.add(Input(shape=(X_train.shape[1],)))  # Verwende Input Layer
    model.add(Dense(64, activation='relu', kernel_initializer=tf.keras.initializers.GlorotUniform(seed=seed)))
    model.add(Dense(32, activation='relu', kernel_initializer=tf.keras.initializers.GlorotUniform(seed=seed)))
    model.add(Dense(1, activation='sigmoid', kernel_initializer=tf.keras.initializers.GlorotUniform(seed=seed)))

    # Kompilieren des Modells
    model.compile(optimizer=Adam(), loss='binary_crossentropy', metrics=['accuracy'])

    # Trainieren des Modells
    model.fit(X_train, y_train, epochs=50, batch_size=10, validation_split=0.2, verbose=0)

    # Evaluiere das Modell
    loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
    print(f"Seed {seed}: Test accuracy = {accuracy}")

    # Speichere die Ergebnisse
    results_seeds.append({"Seed": seed, "Test Accuracy": accuracy})

Seed 2955: Test accuracy = 0.7435897588729858
Seed 1186: Test accuracy = 0.6000000238418579
Seed 6790: Test accuracy = 0.5538461804389954
Seed 4343: Test accuracy = 0.6461538672447205
Seed 72: Test accuracy = 0.7435897588729858
Seed 3923: Test accuracy = 0.446153849363327
Seed 9845: Test accuracy = 0.5846154093742371
Seed 2106: Test accuracy = 0.692307710647583
Seed 2015: Test accuracy = 0.5435897707939148
Seed 2946: Test accuracy = 0.728205144405365
Seed 3667: Test accuracy = 0.7230769395828247
Seed 4640: Test accuracy = 0.6666666865348816
Seed 8351: Test accuracy = 0.6051282286643982
Seed 7077: Test accuracy = 0.5487179756164551
Seed 6297: Test accuracy = 0.5025641322135925
Seed 7328: Test accuracy = 0.7179487347602844
Seed 8007: Test accuracy = 0.7384615540504456
Seed 4217: Test accuracy = 0.5589743852615356
Seed 1991: Test accuracy = 0.692307710647583
Seed 7137: Test accuracy = 0.5743589997291565

In [ ]:
np.random.seed(best_seed)
tf.random.set_seed(best_seed)

categorical_cols = ["Sex", "Ctry", "Town", "Goal of Training",
                    "Preferred Training Daytime", "Subscription Type", "Synchronisation"]
df = df_training_all_features.drop(columns=categorical_cols)  # Ersetze dies mit deiner Datei

# Wähle die Zielvariable und die Features
target_column = "User of latest model"
X = df.drop(columns=[target_column])
y = df[target_column]

# Aufteilung in Trainings- und Testdaten
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = Sequential()
model.add(Input(shape=(X_train.shape[1],)))  # Verwende Input Layer
model.add(Dense(64, activation='relu', kernel_initializer=tf.keras.initializers.GlorotUniform(seed=best_seed)))
model.add(Dense(32, activation='relu', kernel_initializer=tf.keras.initializers.GlorotUniform(seed=best_seed)))
model.add(Dense(1, activation='sigmoid', kernel_initializer=tf.keras.initializers.GlorotUniform(seed=best_seed)))

# Kompilieren des Modells
model.compile(optimizer=Adam(), loss='binary_crossentropy', metrics=['accuracy'])

# Trainieren des Modells
model.fit(X_train, y_train, epochs=100, batch_size=50, validation_split=0.2, verbose=1)

# Evaluiere das Modell auf dem Testdatensatz
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f"Test accuracy: {accuracy}")

# Vorhersagen auf dem Testdatensatz
y_pred = model.predict(X_test)
y_pred_class = (y_pred > 0.5).astype(int)  # Konvertiere die Vorhersagen in 0 oder 1

# Logge die Ergebnisse
df_results = log_model_performance("Best Seed Opt. 100-Epo, 50-BatchS", "Neuronales Netz 3-Layers", y_pred_class, y_test, best_seed)
df_results

Epoch 1/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.5150 - loss: 36.8849 - val_accuracy: 0.5513 - val_loss: 9.4941
Epoch 2/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5767 - loss: 8.1396 - val_accuracy: 0.5449 - val_loss: 10.0246
Epoch 3/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5906 - loss: 5.5359 - val_accuracy: 0.6026 - val_loss: 3.1833
Epoch 4/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6277 - loss: 3.5264 - val_accuracy: 0.6282 - val_loss: 1.8782
Epoch 5/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6495 - loss: 2.0760 - val_accuracy: 0.6474 - val_loss: 1.8594
Epoch 6/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6420 - loss: 1.4259 - val_accuracy: 0.6538 - val_loss: 1.0685
Epoch 7/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6623 - loss: 1.2526 - val_accuracy: 0.6218 - val_loss: 1.5393
Epoch 8/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6764 - loss: 1.2016 - val_accuracy: 0.5385 - val_loss: 3.0696
Epoch 9/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6215 - loss: 2.0794 - val_accuracy: 0.6154 - val_loss: 1.5505
Epoch 10/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6066 - loss: 1.9698 - val_accuracy: 0.6859 - val_loss: 1.0125
Epoch 11/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6494 - loss: 1.4295 - val_accuracy: 0.6410 - val_loss: 1.3801
Epoch 12/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5953 - loss: 2.5054 - val_accuracy: 0.6026 - val_loss: 3.5181
Epoch 13/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6270 - loss: 2.3581 - val_accuracy: 0.5833 - val_loss: 1.6243
Epoch 14/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6080 - loss: 1.7539 - val_accuracy: 0.5449 - val_loss: 3.5911
Epoch 15/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6481 - loss: 1.8138 - val_accuracy: 0.5705 - val_loss: 1.9830
Epoch 16/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6485 - loss: 1.4911 - val_accuracy: 0.5449 - val_loss: 2.5310
Epoch 17/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6242 - loss: 1.6860 - val_accuracy: 0.5385 - val_loss: 2.0923
Epoch 18/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6260 - loss: 1.5107 - val_accuracy: 0.6731 - val_loss: 0.9936
Epoch 19/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6766 - loss: 1.2498 - val_accuracy: 0.7115 - val_loss: 0.9187
Epoch 20/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6665 - loss: 1.2776 - val_accuracy: 0.7179 - val_loss: 1.0966
Epoch 21/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6801 - loss: 1.3847 - val_accuracy: 0.6218 - val_loss: 1.5500
Epoch 22/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6283 - loss: 1.5870 - val_accuracy: 0.6859 - val_loss: 1.0334
Epoch 23/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6780 - loss: 1.0937 - val_accuracy: 0.7244 - val_loss: 0.9174
Epoch 24/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6749 - loss: 1.1560 - val_accuracy: 0.7436 - val_loss: 0.8876
Epoch 25/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6795 - loss: 1.2362 - val_accuracy: 0.6859 - val_loss: 1.2669
Epoch 26/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6003 - loss: 2.4329 - val_accuracy: 0.5897 - val_loss: 3.2890
Epoch 27/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6284 - loss: 2.3154 - val_accuracy: 0.5769 - val_loss: 1.6515
Epoch 28/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6077 - loss: 1.7491 - val_accuracy: 0.5385 - val_loss: 2.4072
Epoch 29/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6523 - loss: 1.5592 - val_accuracy: 0.5449 - val_loss: 2.7252
Epoch 30/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6322 - loss: 1.6130 - val_accuracy: 0.5449 - val_loss: 2.6577
Epoch 31/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6297 - loss: 1.5796 - val_accuracy: 0.5641 - val_loss: 1.8020
Epoch 32/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6624 - loss: 1.3399 - val_accuracy: 0.6282 - val_loss: 1.3729
Epoch 33/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6672 - loss: 1.2931 - val_accuracy: 0.7179 - val_loss: 0.9446
Epoch 34/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6893 - loss: 1.2164 - val_accuracy: 0.7308 - val_loss: 0.8708
Epoch 35/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6936 - loss: 1.1328 - val_accuracy: 0.7051 - val_loss: 1.0414
Epoch 36/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6897 - loss: 1.1860 - val_accuracy: 0.7051 - val_loss: 0.8539
Epoch 37/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6830 - loss: 1.0301 - val_accuracy: 0.7372 - val_loss: 0.8164
Epoch 38/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6778 - loss: 1.2293 - val_accuracy: 0.6923 - val_loss: 1.0553
Epoch 39/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6379 - loss: 1.7234 - val_accuracy: 0.7372 - val_loss: 0.8391
Epoch 40/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7077 - loss: 1.0236 - val_accuracy: 0.6603 - val_loss: 0.9986
Epoch 41/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6864 - loss: 0.9832 - val_accuracy: 0.6538 - val_loss: 1.1079
Epoch 42/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6840 - loss: 0.9644 - val_accuracy: 0.7115 - val_loss: 0.8368
Epoch 43/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6832 - loss: 0.9775 - val_accuracy: 0.7436 - val_loss: 0.7781
Epoch 44/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6572 - loss: 1.1716 - val_accuracy: 0.7051 - val_loss: 0.8861
Epoch 45/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7004 - loss: 0.9844 - val_accuracy: 0.6026 - val_loss: 2.1073
Epoch 46/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6526 - loss: 1.3693 - val_accuracy: 0.6090 - val_loss: 1.7294
Epoch 47/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6918 - loss: 1.0909 - val_accuracy: 0.6026 - val_loss: 1.6446
Epoch 48/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6834 - loss: 1.0337 - val_accuracy: 0.7628 - val_loss: 0.7919
Epoch 49/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6483 - loss: 1.1910 - val_accuracy: 0.6795 - val_loss: 0.9519
Epoch 50/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6958 - loss: 1.0854 - val_accuracy: 0.5833 - val_loss: 2.4927
Epoch 51/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6431 - loss: 1.8669 - val_accuracy: 0.7308 - val_loss: 0.9409
Epoch 52/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6241 - loss: 1.9317 - val_accuracy: 0.5449 - val_loss: 3.6031
Epoch 53/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6716 - loss: 1.9546 - val_accuracy: 0.5962 - val_loss: 1.6433
Epoch 54/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6853 - loss: 1.0721 - val_accuracy: 0.7308 - val_loss: 0.8777
Epoch 55/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6798 - loss: 1.0330 - val_accuracy: 0.7115 - val_loss: 0.8795
Epoch 56/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7253 - loss: 0.9302 - val_accuracy: 0.7436 - val_loss: 0.8158
Epoch 57/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6999 - loss: 0.9346 - val_accuracy: 0.7308 - val_loss: 0.8108
Epoch 58/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7053 - loss: 0.9575 - val_accuracy: 0.7051 - val_loss: 0.9404
Epoch 59/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6979 - loss: 0.9315 - val_accuracy: 0.6026 - val_loss: 1.9189
Epoch 60/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6789 - loss: 1.1810 - val_accuracy: 0.6026 - val_loss: 1.6287
Epoch 61/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6811 - loss: 1.0202 - val_accuracy: 0.7179 - val_loss: 0.8826
Epoch 62/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6560 - loss: 1.2125 - val_accuracy: 0.7308 - val_loss: 0.8056
Epoch 63/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6994 - loss: 0.9211 - val_accuracy: 0.6859 - val_loss: 1.0036
Epoch 64/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7106 - loss: 0.9206 - val_accuracy: 0.6410 - val_loss: 1.2950
Epoch 65/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6754 - loss: 1.1046 - val_accuracy: 0.6410 - val_loss: 1.1174
Epoch 66/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6443 - loss: 1.2666 - val_accuracy: 0.7372 - val_loss: 0.7695
Epoch 67/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6692 - loss: 1.1736 - val_accuracy: 0.6603 - val_loss: 1.4380
Epoch 68/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5796 - loss: 2.4558 - val_accuracy: 0.6731 - val_loss: 1.4210
Epoch 69/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6732 - loss: 1.6967 - val_accuracy: 0.6474 - val_loss: 1.1964
Epoch 70/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6846 - loss: 1.0703 - val_accuracy: 0.7115 - val_loss: 0.9486
Epoch 71/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7179 - loss: 0.9215 - val_accuracy: 0.7115 - val_loss: 0.9110
Epoch 72/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7264 - loss: 0.8699 - val_accuracy: 0.7051 - val_loss: 0.8564
Epoch 73/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7088 - loss: 0.8851 - val_accuracy: 0.7244 - val_loss: 0.8153
Epoch 74/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7074 - loss: 0.8972 - val_accuracy: 0.7115 - val_loss: 0.8474
Epoch 75/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7036 - loss: 0.8598 - val_accuracy: 0.6859 - val_loss: 1.0252
Epoch 76/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6929 - loss: 0.8833 - val_accuracy: 0.7051 - val_loss: 1.0122
Epoch 77/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7058 - loss: 0.8554 - val_accuracy: 0.7244 - val_loss: 0.8002
Epoch 78/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6557 - loss: 1.1452 - val_accuracy: 0.6987 - val_loss: 0.8554
Epoch 79/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6931 - loss: 1.0001 - val_accuracy: 0.6346 - val_loss: 1.6054
Epoch 80/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6856 - loss: 1.1282 - val_accuracy: 0.5769 - val_loss: 1.7677
Epoch 81/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6763 - loss: 1.0241 - val_accuracy: 0.7628 - val_loss: 0.7414
Epoch 82/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6466 - loss: 1.1586 - val_accuracy: 0.7115 - val_loss: 0.8954
Epoch 83/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7052 - loss: 1.0691 - val_accuracy: 0.6859 - val_loss: 0.9940
Epoch 84/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7159 - loss: 0.8715 - val_accuracy: 0.6667 - val_loss: 1.1378
Epoch 85/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6900 - loss: 0.9204 - val_accuracy: 0.7051 - val_loss: 0.8818
Epoch 86/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6432 - loss: 1.2201 - val_accuracy: 0.7115 - val_loss: 0.8256
Epoch 87/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7025 - loss: 0.9906 - val_accuracy: 0.6026 - val_loss: 2.1469
Epoch 88/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6777 - loss: 1.5342 - val_accuracy: 0.6603 - val_loss: 1.0707
Epoch 89/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6555 - loss: 1.2228 - val_accuracy: 0.6667 - val_loss: 1.1320
Epoch 90/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6951 - loss: 1.0811 - val_accuracy: 0.7115 - val_loss: 0.8727
Epoch 91/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7189 - loss: 0.8523 - val_accuracy: 0.7051 - val_loss: 0.8431
Epoch 92/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7150 - loss: 0.8533 - val_accuracy: 0.6987 - val_loss: 0.8714
Epoch 93/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7110 - loss: 0.8456 - val_accuracy: 0.6987 - val_loss: 0.9428
Epoch 94/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7011 - loss: 0.8584 - val_accuracy: 0.7115 - val_loss: 0.8823
Epoch 95/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6940 - loss: 0.8669 - val_accuracy: 0.7244 - val_loss: 0.8018
Epoch 96/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6749 - loss: 0.9618 - val_accuracy: 0.6987 - val_loss: 0.8307
Epoch 97/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7147 - loss: 0.8405 - val_accuracy: 0.6218 - val_loss: 1.6195
Epoch 98/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6892 - loss: 1.0228 - val_accuracy: 0.6538 - val_loss: 1.2326
Epoch 99/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6912 - loss: 0.9834 - val_accuracy: 0.7821 - val_loss: 0.7638
Epoch 100/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6568 - loss: 1.1633 - val_accuracy: 0.6859 - val_loss: 0.9017
Test accuracy: 0.7384615540504456
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step

,Durchlauf,Modell,Seed,Layers,Neurons,Dropout Rate,Batch Normalization,Accuracy,F1 Score
0,"Baseline, 2 Deep-Layers, 32 Neuronen, 50 Epo, 10 BatchS",Neuronales Netz,94,NA,NA,NA,NA,0.656410,0.446281
1,"Baseline, 2 Deep-Layers, 32 Neuronen, 50 Epo, 10 BatchS",Neuronales Netz,60,NA,NA,NA,NA,0.661538,0.679612
2,"Baseline, 50 Epo, 10 BatchS",Neuronales Netz,78,2,32,NA,NA,0.671795,0.695238
3,"Baseline, 50 Epo, 10 BatchS",Neuronales Netz,70,2,32,NA,NA,0.558974,0.638655
4,Optimization,Neuronales Netz,32,"[2, 3]","[32, 64]","[0.2, 0.3]","[True, False]",0.558974,0.638655
5,Optimization,Neuronales Netz,32,"[2, 3]","[32, 64]","[0.2, 0.3]","[True, False]",0.558974,0.638655
6,"Baseline, 100 Epo, 50 BatchS",Neuronales Netz,88,3,64,NA,NA,0.569231,0.045455
7,"Baseline, 100 Epo, 50 BatchS",Neuronales Netz,89,3,64,NA,NA,0.548718,0.633333
8,"Baseline, 100 Epo, 50 BatchS",Neuronales Netz,20,3,64,NA,NA,0.512821,0.615385
9,"Best Seed Opt. 100-Epo, 50-BatchS",Neuronales Netz 3-Layers,1204,NaN,NaN,NaN,NaN,0.738462,0.675159

In [ ]:
np.random.seed(best_seed)
tf.random.set_seed(best_seed)

categorical_cols = ["Sex", "Ctry", "Town", "Goal of Training",
                    "Preferred Training Daytime", "Subscription Type", "Synchronisation"]
df = df_training_all_features.drop(columns=categorical_cols)  # Ersetze dies mit deiner Datei

# Wähle die Zielvariable und die Features
target_column = "User of latest model"
X = df.drop(columns=[target_column])
y = df[target_column]

# Aufteilung in Trainings- und Testdaten
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = Sequential()
model.add(Input(shape=(X_train.shape[1],)))  # Verwende Input Layer
model.add(Dense(64, activation='relu', kernel_initializer=tf.keras.initializers.GlorotUniform(seed=best_seed)))
model.add(Dense(64, activation='relu', kernel_initializer=tf.keras.initializers.GlorotUniform(seed=best_seed)))
model.add(Dense(32, activation='relu', kernel_initializer=tf.keras.initializers.GlorotUniform(seed=best_seed)))
model.add(Dense(1, activation='sigmoid', kernel_initializer=tf.keras.initializers.GlorotUniform(seed=best_seed)))

# Kompilieren des Modells
model.compile(optimizer=Adam(), loss='binary_crossentropy', metrics=['accuracy'])

# Trainieren des Modells
model.fit(X_train, y_train, epochs=100, batch_size=50, validation_split=0.2, verbose=1)

# Evaluiere das Modell auf dem Testdatensatz
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f"Test accuracy: {accuracy}")

# Vorhersagen auf dem Testdatensatz
y_pred = model.predict(X_test)
y_pred_class = (y_pred > 0.5).astype(int)  # Konvertiere die Vorhersagen in 0 oder 1

# Logge die Ergebnisse
df_results = log_model_performance("Best Seed Opt. 100-Epo, 50-BatchS", "Neuronales Netz 4-Layers", y_pred_class, y_test)
df_results

Epoch 1/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 2s 26ms/step - accuracy: 0.4385 - loss: 21.0318 - val_accuracy: 0.5449 - val_loss: 6.5444
Epoch 2/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5650 - loss: 4.4714 - val_accuracy: 0.5449 - val_loss: 5.9100
Epoch 3/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6434 - loss: 2.9248 - val_accuracy: 0.5449 - val_loss: 2.4647
Epoch 4/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5911 - loss: 2.2566 - val_accuracy: 0.5705 - val_loss: 3.1689
Epoch 5/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5574 - loss: 3.0917 - val_accuracy: 0.5064 - val_loss: 3.6188
Epoch 6/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5762 - loss: 2.7867 - val_accuracy: 0.6154 - val_loss: 2.2194
Epoch 7/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5985 - loss: 2.2068 - val_accuracy: 0.6731 - val_loss: 1.0261
Epoch 8/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6711 - loss: 1.3281 - val_accuracy: 0.5064 - val_loss: 5.7604
Epoch 9/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5709 - loss: 5.1367 - val_accuracy: 0.5064 - val_loss: 9.8315
Epoch 10/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5424 - loss: 5.6365 - val_accuracy: 0.6603 - val_loss: 1.2996
Epoch 11/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6396 - loss: 2.3402 - val_accuracy: 0.5513 - val_loss: 3.5656
Epoch 12/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5806 - loss: 3.8207 - val_accuracy: 0.6603 - val_loss: 1.2757
Epoch 13/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6545 - loss: 2.2937 - val_accuracy: 0.5897 - val_loss: 3.1956
Epoch 14/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5912 - loss: 3.7178 - val_accuracy: 0.6667 - val_loss: 1.2190
Epoch 15/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6546 - loss: 2.2006 - val_accuracy: 0.5897 - val_loss: 2.7420
Epoch 16/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5917 - loss: 3.4113 - val_accuracy: 0.6795 - val_loss: 1.1967
Epoch 17/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6440 - loss: 2.2454 - val_accuracy: 0.5769 - val_loss: 2.6331
Epoch 18/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5861 - loss: 3.3375 - val_accuracy: 0.6667 - val_loss: 1.2177
Epoch 19/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6593 - loss: 2.1709 - val_accuracy: 0.6026 - val_loss: 2.4393
Epoch 20/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5829 - loss: 3.1666 - val_accuracy: 0.7051 - val_loss: 1.2874
Epoch 21/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6483 - loss: 2.1830 - val_accuracy: 0.5962 - val_loss: 2.3325
Epoch 22/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5897 - loss: 2.9266 - val_accuracy: 0.5769 - val_loss: 2.3981
Epoch 23/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6816 - loss: 1.5875 - val_accuracy: 0.6667 - val_loss: 1.3088
Epoch 24/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6923 - loss: 1.2325 - val_accuracy: 0.6795 - val_loss: 1.3235
Epoch 25/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6954 - loss: 1.1454 - val_accuracy: 0.7244 - val_loss: 0.9830
Epoch 26/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6642 - loss: 1.2332 - val_accuracy: 0.6859 - val_loss: 1.1384
Epoch 27/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6673 - loss: 1.2223 - val_accuracy: 0.6859 - val_loss: 1.1771
Epoch 28/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6695 - loss: 1.1615 - val_accuracy: 0.6923 - val_loss: 1.0391
Epoch 29/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6964 - loss: 1.1265 - val_accuracy: 0.7244 - val_loss: 0.9170
Epoch 30/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6553 - loss: 1.3744 - val_accuracy: 0.6603 - val_loss: 1.2461
Epoch 31/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6679 - loss: 1.2409 - val_accuracy: 0.6795 - val_loss: 1.1250
Epoch 32/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6480 - loss: 1.2450 - val_accuracy: 0.6410 - val_loss: 1.5535
Epoch 33/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6834 - loss: 1.1312 - val_accuracy: 0.5449 - val_loss: 2.5561
Epoch 34/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6175 - loss: 1.9726 - val_accuracy: 0.6218 - val_loss: 1.4736
Epoch 35/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6004 - loss: 2.3424 - val_accuracy: 0.5449 - val_loss: 4.0363
Epoch 36/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6546 - loss: 1.9891 - val_accuracy: 0.5641 - val_loss: 2.1273
Epoch 37/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6272 - loss: 1.5607 - val_accuracy: 0.7372 - val_loss: 0.9627
Epoch 38/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6605 - loss: 1.3536 - val_accuracy: 0.7308 - val_loss: 0.8886
Epoch 39/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6642 - loss: 1.3751 - val_accuracy: 0.7051 - val_loss: 0.9724
Epoch 40/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7003 - loss: 1.0605 - val_accuracy: 0.5513 - val_loss: 2.7913
Epoch 41/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6733 - loss: 1.7004 - val_accuracy: 0.6603 - val_loss: 1.6297
Epoch 42/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6741 - loss: 1.1216 - val_accuracy: 0.5833 - val_loss: 1.9311
Epoch 43/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6612 - loss: 1.4021 - val_accuracy: 0.6603 - val_loss: 1.4673
Epoch 44/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6864 - loss: 1.1496 - val_accuracy: 0.5449 - val_loss: 2.7926
Epoch 45/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6179 - loss: 1.8380 - val_accuracy: 0.7500 - val_loss: 0.8162
Epoch 46/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6628 - loss: 1.0895 - val_accuracy: 0.5833 - val_loss: 3.0806
Epoch 47/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6407 - loss: 2.1945 - val_accuracy: 0.6731 - val_loss: 1.1144
Epoch 48/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6027 - loss: 2.6226 - val_accuracy: 0.5769 - val_loss: 2.7813
Epoch 49/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6205 - loss: 2.7089 - val_accuracy: 0.5449 - val_loss: 3.3628
Epoch 50/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6621 - loss: 1.7160 - val_accuracy: 0.6731 - val_loss: 1.1071
Epoch 51/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6611 - loss: 1.2801 - val_accuracy: 0.7051 - val_loss: 1.3740
Epoch 52/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6732 - loss: 1.5202 - val_accuracy: 0.6282 - val_loss: 1.1420
Epoch 53/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6605 - loss: 1.0819 - val_accuracy: 0.7115 - val_loss: 1.0762
Epoch 54/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6866 - loss: 1.0400 - val_accuracy: 0.5705 - val_loss: 2.6984
Epoch 55/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6723 - loss: 1.4131 - val_accuracy: 0.6474 - val_loss: 1.5238
Epoch 56/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7094 - loss: 0.9782 - val_accuracy: 0.6923 - val_loss: 1.0808
Epoch 57/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6466 - loss: 1.3063 - val_accuracy: 0.7051 - val_loss: 0.9070
Epoch 58/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6752 - loss: 1.2296 - val_accuracy: 0.6282 - val_loss: 1.5794
Epoch 59/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6627 - loss: 1.5272 - val_accuracy: 0.6859 - val_loss: 1.2852
Epoch 60/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6935 - loss: 1.2489 - val_accuracy: 0.6474 - val_loss: 1.3999
Epoch 61/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7013 - loss: 1.0199 - val_accuracy: 0.6923 - val_loss: 1.0421
Epoch 62/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6754 - loss: 1.3078 - val_accuracy: 0.7115 - val_loss: 0.9003
Epoch 63/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6566 - loss: 1.3152 - val_accuracy: 0.7436 - val_loss: 0.8674
Epoch 64/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6844 - loss: 1.2401 - val_accuracy: 0.6667 - val_loss: 1.2099
Epoch 65/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6819 - loss: 1.1060 - val_accuracy: 0.5513 - val_loss: 2.8619
Epoch 66/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6592 - loss: 1.8626 - val_accuracy: 0.6731 - val_loss: 1.3323
Epoch 67/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6385 - loss: 1.4296 - val_accuracy: 0.6667 - val_loss: 1.5167
Epoch 68/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6978 - loss: 1.0521 - val_accuracy: 0.6282 - val_loss: 1.1867
Epoch 69/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6915 - loss: 1.1577 - val_accuracy: 0.6346 - val_loss: 1.3664
Epoch 70/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6388 - loss: 1.3936 - val_accuracy: 0.7308 - val_loss: 0.8579
Epoch 71/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6709 - loss: 1.1982 - val_accuracy: 0.7179 - val_loss: 0.8518
Epoch 72/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6926 - loss: 1.1540 - val_accuracy: 0.6923 - val_loss: 1.0616
Epoch 73/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7231 - loss: 0.9759 - val_accuracy: 0.5577 - val_loss: 2.8225
Epoch 74/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6765 - loss: 1.6798 - val_accuracy: 0.6731 - val_loss: 1.3815
Epoch 75/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6910 - loss: 1.0823 - val_accuracy: 0.5705 - val_loss: 1.8740
Epoch 76/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6960 - loss: 1.1236 - val_accuracy: 0.6987 - val_loss: 0.9675
Epoch 77/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7153 - loss: 0.9911 - val_accuracy: 0.5897 - val_loss: 1.6324
Epoch 78/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6243 - loss: 1.4668 - val_accuracy: 0.7115 - val_loss: 0.8362
Epoch 79/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6808 - loss: 1.2346 - val_accuracy: 0.6603 - val_loss: 1.3376
Epoch 80/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6450 - loss: 1.3442 - val_accuracy: 0.6603 - val_loss: 1.1566
Epoch 81/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7033 - loss: 0.9602 - val_accuracy: 0.6410 - val_loss: 1.4617
Epoch 82/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6952 - loss: 1.0623 - val_accuracy: 0.6538 - val_loss: 1.1294
Epoch 83/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6525 - loss: 1.3432 - val_accuracy: 0.7179 - val_loss: 0.8554
Epoch 84/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6765 - loss: 1.1989 - val_accuracy: 0.7115 - val_loss: 0.8886
Epoch 85/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7219 - loss: 0.9211 - val_accuracy: 0.5769 - val_loss: 2.1318
Epoch 86/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6926 - loss: 1.1556 - val_accuracy: 0.7051 - val_loss: 0.8761
Epoch 87/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6720 - loss: 1.4254 - val_accuracy: 0.5513 - val_loss: 3.3785
Epoch 88/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6197 - loss: 2.3491 - val_accuracy: 0.7179 - val_loss: 0.9483
Epoch 89/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6427 - loss: 1.5408 - val_accuracy: 0.6923 - val_loss: 1.1429
Epoch 90/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6806 - loss: 1.3021 - val_accuracy: 0.6603 - val_loss: 1.0920
Epoch 91/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7056 - loss: 1.0130 - val_accuracy: 0.6538 - val_loss: 1.2857
Epoch 92/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6811 - loss: 0.9786 - val_accuracy: 0.7115 - val_loss: 0.8405
Epoch 93/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7048 - loss: 0.9669 - val_accuracy: 0.7179 - val_loss: 0.8046
Epoch 94/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6822 - loss: 1.0137 - val_accuracy: 0.6731 - val_loss: 1.0680
Epoch 95/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7048 - loss: 0.9493 - val_accuracy: 0.6026 - val_loss: 1.4638
Epoch 96/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6355 - loss: 1.3836 - val_accuracy: 0.7244 - val_loss: 0.7984
Epoch 97/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6877 - loss: 1.1393 - val_accuracy: 0.6667 - val_loss: 1.3001
Epoch 98/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6413 - loss: 1.3166 - val_accuracy: 0.6603 - val_loss: 1.1826
Epoch 99/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7039 - loss: 0.9277 - val_accuracy: 0.6731 - val_loss: 1.0456
Epoch 100/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7209 - loss: 0.9421 - val_accuracy: 0.5769 - val_loss: 1.6397
Test accuracy: 0.5692307949066162
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step

,Durchlauf,Modell,Accuracy,F1 Score
0,Baseline,Neuronales Netz 2-Schichten 50 Epochen batchsize 10,0.507692,0.625000
1,Baseline,Neuronales Netz 2-Schichten 50 Epochen batchsize 10,0.446154,0.600000
2,"Baseline 50-Epo, 10-BatchS",Neuronales Netz 2-Layers,0.697436,0.628931
3,"Baseline 50-Epo, 10-BatchS",Neuronales Netz 3-Layers,0.569231,0.142857
4,"Best Seed Opt. 50-Epo, 10-BatchS",Neuronales Netz 3-Layers,0.671795,0.457627
5,"Best Seed Opt. 100-Epo, 50-BatchS",Neuronales Netz 3-Layers,0.738462,0.675159
6,"Best Seed Opt. 100-Epo, 50-BatchS",Neuronales Netz 3-Layers,0.584615,0.198020
7,"Best Seed Opt. 50-Epo, 10-BatchS",Neuronales Netz 3-Layers,0.743590,0.691358
8,"Best Seed Opt. 100-Epo, 50-BatchS",Neuronales Netz 3-Layers,0.738462,0.675159
9,"Best Seed Opt. 100-Epo, 50-BatchS",Neuronales Netz 4-Layers,0.569231,0.066667

In [ ]:
categorical_cols = ["Sex", "Ctry", "Town", "Goal of Training",
                    "Preferred Training Daytime", "Subscription Type", "Synchronisation"]
df = df_training_all_features.drop(columns=categorical_cols)
target_column = "User of latest model"
X = df.drop(columns=[target_column])
y = df[target_column]

# Aufteilung in Trainings- und Testdaten
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Liste der Seeds
seeds = [42, 21, 100, 123, 500, 789, 999]

# Speichere die Ergebnisse
results = []

for seed in seeds:
    # Setze Zufallssamen
    np.random.seed(seed)
    tf.random.set_seed(seed)

    # Erstelle das Modell
    model = Sequential()
    model.add(Dense(64, activation='relu', input_shape=(X_train.shape[1],)))
    model.add(Dense(32, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))

    # Kompilieren des Modells
    model.compile(optimizer=Adam(), loss='binary_crossentropy', metrics=['accuracy'])

    # Trainieren des Modells
    model.fit(X_train, y_train, epochs=100, batch_size=50, validation_split=0.2, verbose=0)

    # Evaluiere das Modell
    loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
    print(f"Seed {seed}: Test accuracy = {accuracy}")

    # Speichere die Ergebnisse
    results.append((seed, accuracy))

# Ergebnisse ausgeben
for seed, accuracy in results:
    print(f"Seed {seed}: Test accuracy = {accuracy}")

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Seed 42: Test accuracy = 0.7230769395828247

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Seed 21: Test accuracy = 0.5641025900840759

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Seed 100: Test accuracy = 0.6974359154701233

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Seed 123: Test accuracy = 0.7128205299377441

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Seed 500: Test accuracy = 0.5897436141967773

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Seed 789: Test accuracy = 0.6871795058250427

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Seed 999: Test accuracy = 0.7025641202926636
Seed 42: Test accuracy = 0.7230769395828247
Seed 21: Test accuracy = 0.5641025900840759
Seed 100: Test accuracy = 0.6974359154701233
Seed 123: Test accuracy = 0.7128205299377441
Seed 500: Test accuracy = 0.5897436141967773
Seed 789: Test accuracy = 0.6871795058250427
Seed 999: Test accuracy = 0.7025641202926636

In [ ]:
# Lade dein Daten
# Liste der kategorialen Spalten
categorical_cols = ["Sex", "Ctry", "Town", "Goal of Training",
                    "Preferred Training Daytime", "Subscription Type", "Synchronisation"]
df = df_training_all_features#.drop(columns=categorical_cols)  # Ersetze dies mit deiner Datei

# Wähle die Zielvariable und die Features
target_column = "User of latest model"
X = df.drop(columns=[target_column])
y = df[target_column]



# One-Hot-Encoding für kategoriale Features
categorical_features = ["Sex", "Ctry", "Town", "Goal of Training", "Preferred Training Daytime", "Subscription Type", "Synchronisation"]
X = pd.get_dummies(X, columns=categorical_features, drop_first=True)

# Feature Scaling
#scaler = StandardScaler()
#X_scaled = scaler.fit_transform(X)

# Aufteilung in Trainings- und Testdaten
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Erstelle das neuronale Netz
model = Sequential()
model.add(Dense(64, activation='relu', input_shape=(X_train.shape[1],)))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='sigmoid'))  # Sigmoid-Funktion für binäre Klassifikation

# Kompilieren des Modells
model.compile(optimizer=Adam(), loss='binary_crossentropy', metrics=['accuracy'])

# Trainieren des Modells
model.fit(X_train, y_train, epochs=50, batch_size=10, validation_split=0.2, verbose=1)

# Evaluiere das Modell auf dem Testdatensatz
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f"Test accuracy: {accuracy}")

# Vorhersagen auf dem Testdatensatz
y_pred = model.predict(X_test)
y_pred_class = (y_pred > 0.5).astype(int)  # Konvertiere die Vorhersagen in 0 oder 1

# Logge die Ergebnisse
df_results = log_model_performance("One-Hot Cat", "Neuronales Netz 3-Schichten 50 Epochen batchsize 10", y_pred_class, y_test)
df_results

Epoch 1/50

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

62/62 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.5469 - loss: 18.4748 - val_accuracy: 0.5449 - val_loss: 9.9363
Epoch 2/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5537 - loss: 6.1453 - val_accuracy: 0.5449 - val_loss: 7.3740
Epoch 3/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6390 - loss: 3.1860 - val_accuracy: 0.6346 - val_loss: 1.2801
Epoch 4/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6464 - loss: 1.2297 - val_accuracy: 0.6090 - val_loss: 0.8413
Epoch 5/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6654 - loss: 1.2778 - val_accuracy: 0.5449 - val_loss: 2.8055
Epoch 6/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6165 - loss: 1.6911 - val_accuracy: 0.7115 - val_loss: 0.7312
Epoch 7/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6548 - loss: 1.1313 - val_accuracy: 0.5449 - val_loss: 2.0648
Epoch 8/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6367 - loss: 1.2618 - val_accuracy: 0.5449 - val_loss: 1.3642
Epoch 9/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6517 - loss: 1.1918 - val_accuracy: 0.6859 - val_loss: 0.6923
Epoch 10/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6583 - loss: 0.9904 - val_accuracy: 0.5769 - val_loss: 0.9108
Epoch 11/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7032 - loss: 0.9016 - val_accuracy: 0.5449 - val_loss: 1.6316
Epoch 12/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6517 - loss: 0.9987 - val_accuracy: 0.5449 - val_loss: 1.5050
Epoch 13/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6509 - loss: 0.9362 - val_accuracy: 0.5449 - val_loss: 1.7075
Epoch 14/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6399 - loss: 1.2151 - val_accuracy: 0.6026 - val_loss: 0.8314
Epoch 15/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6940 - loss: 0.8287 - val_accuracy: 0.5449 - val_loss: 1.2281
Epoch 16/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6775 - loss: 0.8567 - val_accuracy: 0.5449 - val_loss: 1.1947
Epoch 17/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6809 - loss: 0.8246 - val_accuracy: 0.5449 - val_loss: 1.2479
Epoch 18/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6729 - loss: 0.7817 - val_accuracy: 0.5577 - val_loss: 1.1210
Epoch 19/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6821 - loss: 0.7720 - val_accuracy: 0.5449 - val_loss: 1.1706
Epoch 20/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6823 - loss: 0.6986 - val_accuracy: 0.6090 - val_loss: 0.7838
Epoch 21/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7142 - loss: 0.7287 - val_accuracy: 0.5641 - val_loss: 0.9532
Epoch 22/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7172 - loss: 0.7065 - val_accuracy: 0.5513 - val_loss: 1.1214
Epoch 23/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7092 - loss: 0.6590 - val_accuracy: 0.6154 - val_loss: 0.7742
Epoch 24/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7301 - loss: 0.6661 - val_accuracy: 0.5641 - val_loss: 1.0647
Epoch 25/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7058 - loss: 0.6511 - val_accuracy: 0.6026 - val_loss: 0.7916
Epoch 26/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7254 - loss: 0.6567 - val_accuracy: 0.5641 - val_loss: 1.0743
Epoch 27/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6911 - loss: 0.7039 - val_accuracy: 0.5577 - val_loss: 1.0776
Epoch 28/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6690 - loss: 0.7552 - val_accuracy: 0.5641 - val_loss: 0.9193
Epoch 29/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7263 - loss: 0.6180 - val_accuracy: 0.6795 - val_loss: 0.6483
Epoch 30/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6950 - loss: 0.6478 - val_accuracy: 0.5641 - val_loss: 1.0032
Epoch 31/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6493 - loss: 0.9102 - val_accuracy: 0.7308 - val_loss: 0.5951
Epoch 32/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7324 - loss: 0.6112 - val_accuracy: 0.6154 - val_loss: 0.7402
Epoch 33/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7060 - loss: 0.7122 - val_accuracy: 0.7115 - val_loss: 0.5984
Epoch 34/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7179 - loss: 0.6694 - val_accuracy: 0.7308 - val_loss: 0.5726
Epoch 35/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7354 - loss: 0.6151 - val_accuracy: 0.7436 - val_loss: 0.5660
Epoch 36/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7268 - loss: 0.6010 - val_accuracy: 0.7564 - val_loss: 0.5656
Epoch 37/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7231 - loss: 0.5960 - val_accuracy: 0.7756 - val_loss: 0.5648
Epoch 38/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7343 - loss: 0.5837 - val_accuracy: 0.7564 - val_loss: 0.5691
Epoch 39/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7288 - loss: 0.5804 - val_accuracy: 0.7564 - val_loss: 0.5847
Epoch 40/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7314 - loss: 0.5929 - val_accuracy: 0.7179 - val_loss: 0.5925
Epoch 41/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7102 - loss: 0.5846 - val_accuracy: 0.7308 - val_loss: 0.6013
Epoch 42/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7377 - loss: 0.5624 - val_accuracy: 0.7244 - val_loss: 0.6159
Epoch 43/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7424 - loss: 0.5680 - val_accuracy: 0.6987 - val_loss: 0.6305
Epoch 44/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7366 - loss: 0.5609 - val_accuracy: 0.7244 - val_loss: 0.6135
Epoch 45/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7503 - loss: 0.5672 - val_accuracy: 0.6346 - val_loss: 0.7208
Epoch 46/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7145 - loss: 0.6945 - val_accuracy: 0.6795 - val_loss: 0.6384
Epoch 47/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7292 - loss: 0.5800 - val_accuracy: 0.7436 - val_loss: 0.5816
Epoch 48/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7456 - loss: 0.5774 - val_accuracy: 0.7244 - val_loss: 0.5779
Epoch 49/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7696 - loss: 0.5391 - val_accuracy: 0.7628 - val_loss: 0.5688
Epoch 50/50
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7607 - loss: 0.5343 - val_accuracy: 0.7628 - val_loss: 0.5423
Test accuracy: 0.764102578163147
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step

,Durchlauf,Modell,Accuracy,F1 Score
0,Baseline,Neuronales Netz 2-Schichten 50 Epochen batchsize 10,0.507692,0.625000
1,Baseline,Neuronales Netz 2-Schichten 50 Epochen batchsize 10,0.446154,0.600000
2,"Baseline 50-Epo, 10-BatchS",Neuronales Netz 2-Layers,0.697436,0.628931
3,"Baseline 50-Epo, 10-BatchS",Neuronales Netz 3-Layers,0.569231,0.142857
4,"Best Seed Opt. 50-Epo, 10-BatchS",Neuronales Netz 3-Layers,0.671795,0.457627
5,"Best Seed Opt. 100-Epo, 50-BatchS",Neuronales Netz 3-Layers,0.738462,0.675159
6,"Best Seed Opt. 100-Epo, 50-BatchS",Neuronales Netz 3-Layers,0.584615,0.198020
7,"Best Seed Opt. 50-Epo, 10-BatchS",Neuronales Netz 3-Layers,0.743590,0.691358
8,"Best Seed Opt. 100-Epo, 50-BatchS",Neuronales Netz 3-Layers,0.738462,0.675159
9,"Best Seed Opt. 100-Epo, 50-BatchS",Neuronales Netz 4-Layers,0.569231,0.066667
10,One-Hot Cat,Neuronales Netz 4-Schichten 50 Epochen batchsize 10,0.758974,0.661871
11,One-Hot Cat,Neuronales Netz 4-Schichten 50 Epochen batchsize 10,0.764103,0.729412

In [ ]:
from tensorflow.keras.layers import Dropout
# Lade dein Daten
# Liste der kategorialen Spalten
categorical_cols = ["Sex", "Ctry", "Town", "Goal of Training",
                    "Preferred Training Daytime", "Subscription Type", "Synchronisation"]
df = df_training_all_features.drop(columns=categorical_cols)  # Ersetze dies mit deiner Datei

# Wähle die Zielvariable und die Features
target_column = "User of latest model"
X = df.drop(columns=[target_column])
y = df[target_column]



# One-Hot-Encoding für kategoriale Features
#categorical_features = ["Sex", "Ctry", "Town", "Goal of Training", "Preferred Training Daytime", "Subscription Type", "Synchronisation"]
#X = pd.get_dummies(X, columns=categorical_features, drop_first=True)

# Feature Scaling
#scaler = StandardScaler()
#X_scaled = scaler.fit_transform(X)

# Aufteilung in Trainings- und Testdaten
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Erstelle das neuronale Netz
model = Sequential()
model.add(Dense(128, activation='relu', input_shape=(X_train.shape[1],)))
model.add(Dropout(0.5))  # 50% der Neuronen werden zufällig deaktiviert
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

# Kompilieren des Modells
model.compile(optimizer=Adam(), loss='binary_crossentropy', metrics=['accuracy'])

# Trainieren des Modells
model.fit(X_train, y_train, epochs=100, batch_size=50, validation_split=0.2, verbose=1)

# Evaluiere das Modell auf dem Testdatensatz
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f"Test accuracy: {accuracy}")

# Vorhersagen auf dem Testdatensatz
y_pred = model.predict(X_test)
y_pred_class = (y_pred > 0.5).astype(int)  # Konvertiere die Vorhersagen in 0 oder 1

# Logge die Ergebnisse
df_results = log_model_performance("Dropout", "Neuronales Netz 4-Schichten 2Dropout 100 Epochen batchsize 50", y_pred_class, y_test)
df_results

Epoch 1/100

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.4549 - loss: 192.3117 - val_accuracy: 0.5449 - val_loss: 83.9776
Epoch 2/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4821 - loss: 121.3513 - val_accuracy: 0.5449 - val_loss: 26.5858
Epoch 3/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4965 - loss: 85.0044 - val_accuracy: 0.5449 - val_loss: 9.3955
Epoch 4/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5106 - loss: 73.1482 - val_accuracy: 0.4615 - val_loss: 26.0858
Epoch 5/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5014 - loss: 58.9342 - val_accuracy: 0.4615 - val_loss: 16.1539
Epoch 6/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5205 - loss: 48.8227 - val_accuracy: 0.4936 - val_loss: 10.3861
Epoch 7/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5338 - loss: 42.9187 - val_accuracy: 0.4615 - val_loss: 14.6790
Epoch 8/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5168 - loss: 34.8660 - val_accuracy: 0.4615 - val_loss: 14.6827
Epoch 9/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.4542 - loss: 35.8617 - val_accuracy: 0.5128 - val_loss: 7.2073
Epoch 10/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5524 - loss: 26.8510 - val_accuracy: 0.5577 - val_loss: 1.8503
Epoch 11/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.4923 - loss: 27.0403 - val_accuracy: 0.5449 - val_loss: 1.6956
Epoch 12/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4766 - loss: 19.7181 - val_accuracy: 0.5449 - val_loss: 4.2911
Epoch 13/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4944 - loss: 21.1445 - val_accuracy: 0.5449 - val_loss: 6.0275
Epoch 14/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5047 - loss: 19.8845 - val_accuracy: 0.5449 - val_loss: 1.9246
Epoch 15/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5252 - loss: 15.6431 - val_accuracy: 0.5449 - val_loss: 1.9333
Epoch 16/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5064 - loss: 11.6158 - val_accuracy: 0.5449 - val_loss: 4.6857
Epoch 17/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5061 - loss: 12.2753 - val_accuracy: 0.5449 - val_loss: 1.9632
Epoch 18/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5271 - loss: 10.3829 - val_accuracy: 0.5449 - val_loss: 1.3128
Epoch 19/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4089 - loss: 11.3017 - val_accuracy: 0.5449 - val_loss: 2.4870
Epoch 20/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5088 - loss: 7.2288 - val_accuracy: 0.5577 - val_loss: 0.7688
Epoch 21/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.4974 - loss: 6.4410 - val_accuracy: 0.5449 - val_loss: 1.1233
Epoch 22/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5465 - loss: 6.6274 - val_accuracy: 0.5769 - val_loss: 0.6724
Epoch 23/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5049 - loss: 6.6300 - val_accuracy: 0.5449 - val_loss: 1.0938
Epoch 24/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5083 - loss: 5.1288 - val_accuracy: 0.5449 - val_loss: 1.1536
Epoch 25/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5385 - loss: 5.1025 - val_accuracy: 0.5449 - val_loss: 1.4051
Epoch 26/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5647 - loss: 4.6756 - val_accuracy: 0.5449 - val_loss: 1.4703
Epoch 27/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5717 - loss: 4.1289 - val_accuracy: 0.5449 - val_loss: 0.7202
Epoch 28/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4983 - loss: 4.0652 - val_accuracy: 0.5449 - val_loss: 0.8172
Epoch 29/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5236 - loss: 3.4680 - val_accuracy: 0.5449 - val_loss: 0.9220
Epoch 30/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5698 - loss: 2.9570 - val_accuracy: 0.5577 - val_loss: 0.6776
Epoch 31/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5263 - loss: 2.6113 - val_accuracy: 0.5385 - val_loss: 0.6894
Epoch 32/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5247 - loss: 2.3111 - val_accuracy: 0.6282 - val_loss: 0.6661
Epoch 33/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.4928 - loss: 2.3465 - val_accuracy: 0.5449 - val_loss: 0.7613
Epoch 34/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5581 - loss: 2.2631 - val_accuracy: 0.5449 - val_loss: 0.7311
Epoch 35/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5271 - loss: 2.6386 - val_accuracy: 0.5449 - val_loss: 0.7680
Epoch 36/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5675 - loss: 1.6843 - val_accuracy: 0.5449 - val_loss: 0.9015
Epoch 37/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5694 - loss: 1.8669 - val_accuracy: 0.5449 - val_loss: 0.7611
Epoch 38/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5451 - loss: 1.8783 - val_accuracy: 0.5449 - val_loss: 0.8103
Epoch 39/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5617 - loss: 1.5657 - val_accuracy: 0.5449 - val_loss: 0.7102
Epoch 40/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5497 - loss: 1.8997 - val_accuracy: 0.5449 - val_loss: 0.8893
Epoch 41/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5877 - loss: 1.4327 - val_accuracy: 0.5449 - val_loss: 1.0385
Epoch 42/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5299 - loss: 1.6139 - val_accuracy: 0.5449 - val_loss: 0.7699
Epoch 43/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5575 - loss: 1.2757 - val_accuracy: 0.5449 - val_loss: 0.8021
Epoch 44/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5846 - loss: 1.3473 - val_accuracy: 0.5449 - val_loss: 0.6874
Epoch 45/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5884 - loss: 1.1887 - val_accuracy: 0.5449 - val_loss: 0.8361
Epoch 46/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5737 - loss: 1.0283 - val_accuracy: 0.5449 - val_loss: 0.7034
Epoch 47/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5629 - loss: 1.2529 - val_accuracy: 0.5769 - val_loss: 0.6694
Epoch 48/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5408 - loss: 1.1861 - val_accuracy: 0.5449 - val_loss: 0.7160
Epoch 49/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5810 - loss: 1.1666 - val_accuracy: 0.6090 - val_loss: 0.6658
Epoch 50/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5639 - loss: 1.1422 - val_accuracy: 0.5449 - val_loss: 0.6923
Epoch 51/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5949 - loss: 1.1070 - val_accuracy: 0.6026 - val_loss: 0.6773
Epoch 52/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5979 - loss: 1.1024 - val_accuracy: 0.5513 - val_loss: 0.6880
Epoch 53/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5470 - loss: 1.1384 - val_accuracy: 0.5449 - val_loss: 0.7307
Epoch 54/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5579 - loss: 1.0856 - val_accuracy: 0.5449 - val_loss: 0.7035
Epoch 55/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5649 - loss: 0.9606 - val_accuracy: 0.5449 - val_loss: 0.6757
Epoch 56/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6063 - loss: 0.8197 - val_accuracy: 0.5449 - val_loss: 0.6906
Epoch 57/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5713 - loss: 0.8877 - val_accuracy: 0.6026 - val_loss: 0.6619
Epoch 58/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5985 - loss: 0.8383 - val_accuracy: 0.5449 - val_loss: 0.7096
Epoch 59/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5792 - loss: 0.8533 - val_accuracy: 0.6090 - val_loss: 0.6637
Epoch 60/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5881 - loss: 1.0266 - val_accuracy: 0.5449 - val_loss: 0.7062
Epoch 61/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5839 - loss: 0.8898 - val_accuracy: 0.5449 - val_loss: 0.7032
Epoch 62/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5949 - loss: 0.8404 - val_accuracy: 0.5449 - val_loss: 0.8220
Epoch 63/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5942 - loss: 1.0297 - val_accuracy: 0.5449 - val_loss: 0.7094
Epoch 64/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6327 - loss: 0.9231 - val_accuracy: 0.5449 - val_loss: 0.7140
Epoch 65/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5888 - loss: 0.8986 - val_accuracy: 0.5449 - val_loss: 0.6917
Epoch 66/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5984 - loss: 0.9831 - val_accuracy: 0.5513 - val_loss: 0.6891
Epoch 67/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5431 - loss: 1.0600 - val_accuracy: 0.5449 - val_loss: 0.6918
Epoch 68/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6063 - loss: 0.9192 - val_accuracy: 0.5449 - val_loss: 0.8076
Epoch 69/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6250 - loss: 0.8454 - val_accuracy: 0.5449 - val_loss: 0.9762
Epoch 70/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5870 - loss: 0.8433 - val_accuracy: 0.6154 - val_loss: 0.6668
Epoch 71/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5790 - loss: 0.9364 - val_accuracy: 0.5833 - val_loss: 0.6710
Epoch 72/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5361 - loss: 0.9001 - val_accuracy: 0.5833 - val_loss: 0.6714
Epoch 73/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5683 - loss: 0.9237 - val_accuracy: 0.5449 - val_loss: 0.6774
Epoch 74/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5922 - loss: 0.7417 - val_accuracy: 0.5449 - val_loss: 0.7347
Epoch 75/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6033 - loss: 0.7135 - val_accuracy: 0.5449 - val_loss: 0.7195
Epoch 76/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5584 - loss: 0.7832 - val_accuracy: 0.6282 - val_loss: 0.6649
Epoch 77/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6068 - loss: 0.8866 - val_accuracy: 0.5449 - val_loss: 0.7404
Epoch 78/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6201 - loss: 0.7610 - val_accuracy: 0.5449 - val_loss: 0.7172
Epoch 79/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6026 - loss: 0.8078 - val_accuracy: 0.5449 - val_loss: 0.6802
Epoch 80/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5926 - loss: 0.6955 - val_accuracy: 0.5449 - val_loss: 0.7614
Epoch 81/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6194 - loss: 0.7235 - val_accuracy: 0.5449 - val_loss: 0.7229
Epoch 82/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6096 - loss: 0.7870 - val_accuracy: 0.5449 - val_loss: 0.7900
Epoch 83/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6020 - loss: 0.7889 - val_accuracy: 0.5449 - val_loss: 0.7699
Epoch 84/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6143 - loss: 0.8528 - val_accuracy: 0.5449 - val_loss: 0.7556
Epoch 85/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6076 - loss: 0.8045 - val_accuracy: 0.5449 - val_loss: 0.7548
Epoch 86/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5961 - loss: 0.8066 - val_accuracy: 0.5449 - val_loss: 0.6851
Epoch 87/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5961 - loss: 0.7260 - val_accuracy: 0.5449 - val_loss: 0.7205
Epoch 88/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6099 - loss: 0.7596 - val_accuracy: 0.5449 - val_loss: 0.7250
Epoch 89/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5893 - loss: 0.7418 - val_accuracy: 0.5385 - val_loss: 0.6867
Epoch 90/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6065 - loss: 0.8512 - val_accuracy: 0.5449 - val_loss: 0.7106
Epoch 91/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6050 - loss: 0.8183 - val_accuracy: 0.5449 - val_loss: 0.7098
Epoch 92/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6170 - loss: 0.8100 - val_accuracy: 0.5577 - val_loss: 0.6733
Epoch 93/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6030 - loss: 0.7726 - val_accuracy: 0.5449 - val_loss: 0.6855
Epoch 94/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6069 - loss: 0.8216 - val_accuracy: 0.5449 - val_loss: 0.6894
Epoch 95/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5963 - loss: 0.7814 - val_accuracy: 0.5449 - val_loss: 0.7115
Epoch 96/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5691 - loss: 0.7842 - val_accuracy: 0.5449 - val_loss: 0.7882
Epoch 97/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6169 - loss: 0.7259 - val_accuracy: 0.5449 - val_loss: 0.7669
Epoch 98/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6308 - loss: 0.7410 - val_accuracy: 0.5449 - val_loss: 0.7852
Epoch 99/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6343 - loss: 0.7348 - val_accuracy: 0.5449 - val_loss: 0.7225
Epoch 100/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6118 - loss: 0.7127 - val_accuracy: 0.5449 - val_loss: 0.6907
Test accuracy: 0.5589743852615356
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step

,Durchlauf,Modell,Accuracy,F1 Score
0,Baseline,Neuronales Netz 2-Schichten 50 Epochen batchsize 10,0.507692,0.625000
1,Baseline,Neuronales Netz 2-Schichten 50 Epochen batchsize 10,0.446154,0.600000
2,"Baseline 50-Epo, 10-BatchS",Neuronales Netz 2-Layers,0.697436,0.628931
3,"Baseline 50-Epo, 10-BatchS",Neuronales Netz 3-Layers,0.569231,0.142857
4,"Best Seed Opt. 50-Epo, 10-BatchS",Neuronales Netz 3-Layers,0.671795,0.457627
5,"Best Seed Opt. 100-Epo, 50-BatchS",Neuronales Netz 3-Layers,0.738462,0.675159
6,"Best Seed Opt. 100-Epo, 50-BatchS",Neuronales Netz 3-Layers,0.584615,0.198020
7,"Best Seed Opt. 50-Epo, 10-BatchS",Neuronales Netz 3-Layers,0.743590,0.691358
8,"Best Seed Opt. 100-Epo, 50-BatchS",Neuronales Netz 3-Layers,0.738462,0.675159
9,"Best Seed Opt. 100-Epo, 50-BatchS",Neuronales Netz 4-Layers,0.569231,0.066667
10,One-Hot Cat,Neuronales Netz 4-Schichten 50 Epochen batchsize 10,0.758974,0.661871
11,One-Hot Cat,Neuronales Netz 4-Schichten 50 Epochen batchsize 10,0.764103,0.729412
12,Dropout,Neuronales Netz 4-Schichten 2Dropout 100 Epochen batchsize 50,0.558974,0.000000

In [ ]:
from tensorflow.keras.layers import Dropout
# Lade dein Daten
# Liste der kategorialen Spalten
categorical_cols = ["Sex", "Ctry", "Town", "Goal of Training",
                    "Preferred Training Daytime", "Subscription Type", "Synchronisation"]
df = df_training_all_features.drop(columns=categorical_cols)  # Ersetze dies mit deiner Datei

# Wähle die Zielvariable und die Features
target_column = "User of latest model"
X = df.drop(columns=[target_column])
y = df[target_column]



# One-Hot-Encoding für kategoriale Features
#categorical_features = ["Sex", "Ctry", "Town", "Goal of Training", "Preferred Training Daytime", "Subscription Type", "Synchronisation"]
#X = pd.get_dummies(X, columns=categorical_features, drop_first=True)

# Feature Scaling
#scaler = StandardScaler()
#X_scaled = scaler.fit_transform(X)

# Aufteilung in Trainings- und Testdaten
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Erstelle das neuronale Netz
model = Sequential()
model.add(Dense(128, activation='relu', input_shape=(X_train.shape[1],)))
model.add(Dropout(0.2))  # 50% der Neuronen werden zufällig deaktiviert
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

# Kompilieren des Modells
model.compile(optimizer=Adam(), loss='binary_crossentropy', metrics=['accuracy'])

# Trainieren des Modells
model.fit(X_train, y_train, epochs=100, batch_size=50, validation_split=0.2, verbose=1)

# Evaluiere das Modell auf dem Testdatensatz
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f"Test accuracy: {accuracy}")

# Vorhersagen auf dem Testdatensatz
y_pred = model.predict(X_test)
y_pred_class = (y_pred > 0.5).astype(int)  # Konvertiere die Vorhersagen in 0 oder 1

# Logge die Ergebnisse
df_results = log_model_performance("Dropout 0.2", "Neuronales Netz 4-Schichten 2Dropout 100 Epochen batchsize 50", y_pred_class, y_test)
df_results

Epoch 1/100

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

13/13 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - accuracy: 0.4963 - loss: 103.3655 - val_accuracy: 0.6218 - val_loss: 3.4712
Epoch 2/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5164 - loss: 51.7412 - val_accuracy: 0.5449 - val_loss: 46.2857
Epoch 3/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5452 - loss: 36.2542 - val_accuracy: 0.5128 - val_loss: 13.7979
Epoch 4/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5401 - loss: 29.3437 - val_accuracy: 0.4936 - val_loss: 13.0330
Epoch 5/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5065 - loss: 22.9680 - val_accuracy: 0.4679 - val_loss: 5.4110
Epoch 6/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5512 - loss: 16.7241 - val_accuracy: 0.5449 - val_loss: 3.0365
Epoch 7/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5422 - loss: 14.0486 - val_accuracy: 0.5192 - val_loss: 4.9119
Epoch 8/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5058 - loss: 9.9421 - val_accuracy: 0.5833 - val_loss: 0.9092
Epoch 9/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5067 - loss: 9.2732 - val_accuracy: 0.5513 - val_loss: 1.2238
Epoch 10/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5346 - loss: 7.0814 - val_accuracy: 0.4679 - val_loss: 2.5692
Epoch 11/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4838 - loss: 6.9893 - val_accuracy: 0.5449 - val_loss: 1.4685
Epoch 12/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4961 - loss: 5.5328 - val_accuracy: 0.5385 - val_loss: 1.4058
Epoch 13/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5310 - loss: 5.5076 - val_accuracy: 0.5000 - val_loss: 0.8463
Epoch 14/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5185 - loss: 6.1161 - val_accuracy: 0.4936 - val_loss: 1.3553
Epoch 15/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4798 - loss: 5.5524 - val_accuracy: 0.4679 - val_loss: 2.2249
Epoch 16/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5467 - loss: 3.2896 - val_accuracy: 0.4936 - val_loss: 1.0886
Epoch 17/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5225 - loss: 4.2783 - val_accuracy: 0.4679 - val_loss: 1.9283
Epoch 18/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5188 - loss: 3.4441 - val_accuracy: 0.4615 - val_loss: 2.2973
Epoch 19/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4716 - loss: 3.3333 - val_accuracy: 0.5000 - val_loss: 1.4288
Epoch 20/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5090 - loss: 3.5744 - val_accuracy: 0.5385 - val_loss: 1.2436
Epoch 21/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5348 - loss: 2.8965 - val_accuracy: 0.5128 - val_loss: 1.2496
Epoch 22/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5084 - loss: 2.9606 - val_accuracy: 0.4679 - val_loss: 1.3138
Epoch 23/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5434 - loss: 2.5722 - val_accuracy: 0.4744 - val_loss: 1.2887
Epoch 24/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4911 - loss: 2.4662 - val_accuracy: 0.4679 - val_loss: 1.5453
Epoch 25/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5262 - loss: 2.2316 - val_accuracy: 0.4872 - val_loss: 1.2553
Epoch 26/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4742 - loss: 2.7167 - val_accuracy: 0.4679 - val_loss: 1.3883
Epoch 27/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5396 - loss: 2.3399 - val_accuracy: 0.4615 - val_loss: 1.7400
Epoch 28/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5205 - loss: 2.0132 - val_accuracy: 0.4679 - val_loss: 1.6172
Epoch 29/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4864 - loss: 1.9108 - val_accuracy: 0.4679 - val_loss: 1.2384
Epoch 30/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4960 - loss: 1.7044 - val_accuracy: 0.5000 - val_loss: 0.9995
Epoch 31/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5772 - loss: 1.6007 - val_accuracy: 0.5064 - val_loss: 0.9855
Epoch 32/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5543 - loss: 1.7080 - val_accuracy: 0.5449 - val_loss: 0.7671
Epoch 33/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5915 - loss: 2.1556 - val_accuracy: 0.5449 - val_loss: 0.9333
Epoch 34/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5832 - loss: 1.3107 - val_accuracy: 0.5449 - val_loss: 0.9505
Epoch 35/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5605 - loss: 1.5076 - val_accuracy: 0.5449 - val_loss: 0.7061
Epoch 36/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5761 - loss: 1.3626 - val_accuracy: 0.5449 - val_loss: 1.1158
Epoch 37/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5962 - loss: 1.4364 - val_accuracy: 0.5385 - val_loss: 0.6915
Epoch 38/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5643 - loss: 1.2783 - val_accuracy: 0.5449 - val_loss: 0.9228
Epoch 39/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5741 - loss: 1.1345 - val_accuracy: 0.5449 - val_loss: 0.7783
Epoch 40/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5358 - loss: 1.2275 - val_accuracy: 0.5449 - val_loss: 0.7688
Epoch 41/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6176 - loss: 0.9217 - val_accuracy: 0.5449 - val_loss: 0.7286
Epoch 42/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5411 - loss: 1.4284 - val_accuracy: 0.5449 - val_loss: 0.6973
Epoch 43/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5915 - loss: 1.0245 - val_accuracy: 0.6026 - val_loss: 0.6678
Epoch 44/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5232 - loss: 0.9931 - val_accuracy: 0.5449 - val_loss: 0.8726
Epoch 45/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5434 - loss: 1.0855 - val_accuracy: 0.5449 - val_loss: 0.6947
Epoch 46/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.5798 - loss: 0.9666 - val_accuracy: 0.6026 - val_loss: 0.6761
Epoch 47/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5202 - loss: 0.9087 - val_accuracy: 0.5449 - val_loss: 0.6882
Epoch 48/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5646 - loss: 0.9718 - val_accuracy: 0.5449 - val_loss: 0.6941
Epoch 49/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5346 - loss: 1.0325 - val_accuracy: 0.5449 - val_loss: 0.7719
Epoch 50/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5277 - loss: 0.8972 - val_accuracy: 0.5449 - val_loss: 0.7722
Epoch 51/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5880 - loss: 0.9160 - val_accuracy: 0.5449 - val_loss: 0.7484
Epoch 52/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5637 - loss: 1.0082 - val_accuracy: 0.5449 - val_loss: 0.7096
Epoch 53/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5824 - loss: 0.8607 - val_accuracy: 0.5449 - val_loss: 0.7013
Epoch 54/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5487 - loss: 0.8809 - val_accuracy: 0.5449 - val_loss: 0.6911
Epoch 55/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5626 - loss: 0.8922 - val_accuracy: 0.5449 - val_loss: 0.8006
Epoch 56/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5331 - loss: 0.8906 - val_accuracy: 0.5449 - val_loss: 0.7270
Epoch 57/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5831 - loss: 0.8259 - val_accuracy: 0.5385 - val_loss: 0.6777
Epoch 58/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4917 - loss: 0.9273 - val_accuracy: 0.5449 - val_loss: 0.7071
Epoch 59/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5707 - loss: 0.8531 - val_accuracy: 0.5449 - val_loss: 0.7000
Epoch 60/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5578 - loss: 0.8328 - val_accuracy: 0.6026 - val_loss: 0.6730
Epoch 61/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5448 - loss: 0.8287 - val_accuracy: 0.5449 - val_loss: 0.7932
Epoch 62/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5669 - loss: 0.8274 - val_accuracy: 0.5769 - val_loss: 0.6736
Epoch 63/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5551 - loss: 0.8350 - val_accuracy: 0.5449 - val_loss: 0.7071
Epoch 64/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5800 - loss: 0.7605 - val_accuracy: 0.5449 - val_loss: 0.6800
Epoch 65/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5916 - loss: 0.8304 - val_accuracy: 0.5449 - val_loss: 0.6935
Epoch 66/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5733 - loss: 0.7863 - val_accuracy: 0.5449 - val_loss: 0.6756
Epoch 67/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5665 - loss: 0.7651 - val_accuracy: 0.5449 - val_loss: 0.6899
Epoch 68/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5418 - loss: 0.8163 - val_accuracy: 0.5449 - val_loss: 0.7079
Epoch 69/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5269 - loss: 0.8349 - val_accuracy: 0.5449 - val_loss: 0.6895
Epoch 70/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5768 - loss: 0.8452 - val_accuracy: 0.5449 - val_loss: 0.7865
Epoch 71/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5723 - loss: 0.8284 - val_accuracy: 0.5449 - val_loss: 0.7257
Epoch 72/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5864 - loss: 0.7209 - val_accuracy: 0.5449 - val_loss: 0.6815
Epoch 73/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5539 - loss: 0.7814 - val_accuracy: 0.5449 - val_loss: 0.6941
Epoch 74/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5599 - loss: 0.7650 - val_accuracy: 0.6346 - val_loss: 0.6699
Epoch 75/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5644 - loss: 0.8497 - val_accuracy: 0.5641 - val_loss: 0.6735
Epoch 76/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5181 - loss: 0.8115 - val_accuracy: 0.5385 - val_loss: 0.6717
Epoch 77/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5701 - loss: 0.7798 - val_accuracy: 0.5449 - val_loss: 0.7194
Epoch 78/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6205 - loss: 0.7295 - val_accuracy: 0.5449 - val_loss: 0.6908
Epoch 79/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5930 - loss: 0.8257 - val_accuracy: 0.5449 - val_loss: 0.6873
Epoch 80/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5594 - loss: 0.7535 - val_accuracy: 0.5449 - val_loss: 0.7170
Epoch 81/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5657 - loss: 0.7929 - val_accuracy: 0.5449 - val_loss: 0.6958
Epoch 82/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5619 - loss: 0.7661 - val_accuracy: 0.5449 - val_loss: 0.7418
Epoch 83/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5619 - loss: 0.7654 - val_accuracy: 0.5449 - val_loss: 0.8066
Epoch 84/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5833 - loss: 0.7923 - val_accuracy: 0.5577 - val_loss: 0.6704
Epoch 85/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6092 - loss: 0.7752 - val_accuracy: 0.5449 - val_loss: 0.7191
Epoch 86/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5823 - loss: 0.8176 - val_accuracy: 0.5449 - val_loss: 0.7116
Epoch 87/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5782 - loss: 0.7581 - val_accuracy: 0.5449 - val_loss: 0.6808
Epoch 88/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6003 - loss: 0.6943 - val_accuracy: 0.5385 - val_loss: 0.6740
Epoch 89/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6006 - loss: 0.7301 - val_accuracy: 0.5449 - val_loss: 0.7301
Epoch 90/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5569 - loss: 0.7587 - val_accuracy: 0.5449 - val_loss: 0.6804
Epoch 91/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5798 - loss: 0.7471 - val_accuracy: 0.5449 - val_loss: 0.6906
Epoch 92/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5632 - loss: 0.7728 - val_accuracy: 0.5449 - val_loss: 0.7300
Epoch 93/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5839 - loss: 0.7660 - val_accuracy: 0.6026 - val_loss: 0.6655
Epoch 94/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5944 - loss: 0.7359 - val_accuracy: 0.6282 - val_loss: 0.6671
Epoch 95/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5502 - loss: 0.7441 - val_accuracy: 0.6026 - val_loss: 0.6683
Epoch 96/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5666 - loss: 0.7618 - val_accuracy: 0.5449 - val_loss: 0.8496
Epoch 97/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5561 - loss: 0.7824 - val_accuracy: 0.6154 - val_loss: 0.6664
Epoch 98/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5887 - loss: 0.7255 - val_accuracy: 0.5962 - val_loss: 0.6691
Epoch 99/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6206 - loss: 0.7113 - val_accuracy: 0.5769 - val_loss: 0.6721
Epoch 100/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5850 - loss: 0.7256 - val_accuracy: 0.6218 - val_loss: 0.6679
Test accuracy: 0.6256410479545593
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step

,Durchlauf,Modell,Accuracy,F1 Score
0,Baseline,Neuronales Netz 2-Schichten 50 Epochen batchsize 10,0.507692,0.625000
1,Baseline,Neuronales Netz 2-Schichten 50 Epochen batchsize 10,0.446154,0.600000
2,"Baseline 50-Epo, 10-BatchS",Neuronales Netz 2-Layers,0.697436,0.628931
3,"Baseline 50-Epo, 10-BatchS",Neuronales Netz 3-Layers,0.569231,0.142857
4,"Best Seed Opt. 50-Epo, 10-BatchS",Neuronales Netz 3-Layers,0.671795,0.457627
5,"Best Seed Opt. 100-Epo, 50-BatchS",Neuronales Netz 3-Layers,0.738462,0.675159
6,"Best Seed Opt. 100-Epo, 50-BatchS",Neuronales Netz 3-Layers,0.584615,0.198020
7,"Best Seed Opt. 50-Epo, 10-BatchS",Neuronales Netz 3-Layers,0.743590,0.691358
8,"Best Seed Opt. 100-Epo, 50-BatchS",Neuronales Netz 3-Layers,0.738462,0.675159
9,"Best Seed Opt. 100-Epo, 50-BatchS",Neuronales Netz 4-Layers,0.569231,0.066667
10,One-Hot Cat,Neuronales Netz 4-Schichten 50 Epochen batchsize 10,0.758974,0.661871
11,One-Hot Cat,Neuronales Netz 4-Schichten 50 Epochen batchsize 10,0.764103,0.729412
12,Dropout,Neuronales Netz 4-Schichten 2Dropout 100 Epochen batchsize 50,0.558974,0.000000
13,Dropout 0.2,Neuronales Netz 4-Schichten 2Dropout 100 Epochen batchsize 50,0.625641,0.365217

In [ ]:
# Baseline-Modellierung
def create_model(seeds, layers, neurons, dropout_rate=0.0, batch_norm=False):
    model = Sequential()
    model.add(Input(shape=(X_train.shape[1],)))
    for _ in range(layers):
        model.add(Dense(neurons, activation='relu',kernel_initializer=tf.keras.initializers.GlorotUniform(seed=seeds)))
        if batch_norm:
            model.add(BatchNormalization())
        if dropout_rate > 0:
            model.add(Dropout(dropout_rate))
    model.add(Dense(1, activation='sigmoid'))
    return model

model = create_model(2856,4,32,0.2,True)
# Kompilieren des Modells
model.compile(optimizer=Adam(), loss='binary_crossentropy', metrics=['accuracy'])

# Trainieren des Modells
model.fit(X_train, y_train, epochs=100, batch_size=50, validation_split=0.2, verbose=1)

# Evaluiere das Modell auf dem Testdatensatz
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f"Test accuracy: {accuracy}")

# Vorhersagen auf dem Testdatensatz
y_pred = model.predict(X_test)
y_pred_class = (y_pred > 0.5).astype(int)  # Konvertiere die Vorhersagen in 0 oder 1

# Logge die Ergebnisse
df_results = log_model_performance("Dropout 0.2, seed 2856", "Neuronales Netz 4-Schichten 2Dropout 100 Epochen batchsize 50", y_pred_class, y_test)
df_results

Epoch 1/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 3s 26ms/step - accuracy: 0.5040 - loss: 0.8356 - val_accuracy: 0.4551 - val_loss: 1.1949
Epoch 2/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6084 - loss: 0.7798 - val_accuracy: 0.4551 - val_loss: 0.9055
Epoch 3/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6194 - loss: 0.7226 - val_accuracy: 0.4679 - val_loss: 0.8325
Epoch 4/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6066 - loss: 0.7215 - val_accuracy: 0.4551 - val_loss: 0.9876
Epoch 5/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6101 - loss: 0.6866 - val_accuracy: 0.5321 - val_loss: 0.9818
Epoch 6/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6222 - loss: 0.7066 - val_accuracy: 0.5513 - val_loss: 0.7969
Epoch 7/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6494 - loss: 0.7037 - val_accuracy: 0.6026 - val_loss: 0.7064
Epoch 8/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6235 - loss: 0.6597 - val_accuracy: 0.5897 - val_loss: 0.6898
Epoch 9/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6012 - loss: 0.7043 - val_accuracy: 0.6154 - val_loss: 0.6644
Epoch 10/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6175 - loss: 0.6697 - val_accuracy: 0.6090 - val_loss: 0.6568
Epoch 11/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6346 - loss: 0.6767 - val_accuracy: 0.6346 - val_loss: 0.6608
Epoch 12/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6254 - loss: 0.6870 - val_accuracy: 0.5641 - val_loss: 0.6867
Epoch 13/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6597 - loss: 0.6686 - val_accuracy: 0.6282 - val_loss: 0.6561
Epoch 14/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6513 - loss: 0.6423 - val_accuracy: 0.6282 - val_loss: 0.6548
Epoch 15/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6609 - loss: 0.6356 - val_accuracy: 0.6410 - val_loss: 0.6505
Epoch 16/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6660 - loss: 0.6111 - val_accuracy: 0.6346 - val_loss: 0.6555
Epoch 17/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6584 - loss: 0.6383 - val_accuracy: 0.6410 - val_loss: 0.6599
Epoch 18/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6738 - loss: 0.6250 - val_accuracy: 0.6282 - val_loss: 0.6375
Epoch 19/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6676 - loss: 0.6202 - val_accuracy: 0.5513 - val_loss: 0.6990
Epoch 20/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6978 - loss: 0.6153 - val_accuracy: 0.5705 - val_loss: 0.6999
Epoch 21/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6692 - loss: 0.6265 - val_accuracy: 0.6026 - val_loss: 0.6803
Epoch 22/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6744 - loss: 0.6107 - val_accuracy: 0.5513 - val_loss: 0.7255
Epoch 23/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6869 - loss: 0.6008 - val_accuracy: 0.6538 - val_loss: 0.6607
Epoch 24/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6949 - loss: 0.5996 - val_accuracy: 0.6795 - val_loss: 0.6442
Epoch 25/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6868 - loss: 0.6107 - val_accuracy: 0.6987 - val_loss: 0.6496
Epoch 26/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6769 - loss: 0.6182 - val_accuracy: 0.5449 - val_loss: 0.7650
Epoch 27/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7020 - loss: 0.6144 - val_accuracy: 0.6795 - val_loss: 0.6181
Epoch 28/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6675 - loss: 0.5977 - val_accuracy: 0.5513 - val_loss: 0.7461
Epoch 29/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7055 - loss: 0.6133 - val_accuracy: 0.6410 - val_loss: 0.6781
Epoch 30/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7050 - loss: 0.6022 - val_accuracy: 0.5513 - val_loss: 0.7296
Epoch 31/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6880 - loss: 0.5767 - val_accuracy: 0.6923 - val_loss: 0.6120
Epoch 32/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6675 - loss: 0.6301 - val_accuracy: 0.6795 - val_loss: 0.5942
Epoch 33/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7285 - loss: 0.5630 - val_accuracy: 0.6410 - val_loss: 0.6333
Epoch 34/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6931 - loss: 0.5813 - val_accuracy: 0.5833 - val_loss: 0.7031
Epoch 35/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7185 - loss: 0.5706 - val_accuracy: 0.6795 - val_loss: 0.5908
Epoch 36/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7063 - loss: 0.5854 - val_accuracy: 0.5577 - val_loss: 0.7298
Epoch 37/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7366 - loss: 0.5494 - val_accuracy: 0.5577 - val_loss: 0.7817
Epoch 38/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7425 - loss: 0.5495 - val_accuracy: 0.6987 - val_loss: 0.6022
Epoch 39/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6835 - loss: 0.6055 - val_accuracy: 0.5449 - val_loss: 0.8384
Epoch 40/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7044 - loss: 0.5987 - val_accuracy: 0.6987 - val_loss: 0.5817
Epoch 41/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7086 - loss: 0.5810 - val_accuracy: 0.5449 - val_loss: 0.7566
Epoch 42/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7191 - loss: 0.5752 - val_accuracy: 0.6538 - val_loss: 0.6207
Epoch 43/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7509 - loss: 0.5637 - val_accuracy: 0.5449 - val_loss: 0.7742
Epoch 44/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7308 - loss: 0.5545 - val_accuracy: 0.5962 - val_loss: 0.7219
Epoch 45/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7041 - loss: 0.5818 - val_accuracy: 0.5449 - val_loss: 0.8805
Epoch 46/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7211 - loss: 0.5517 - val_accuracy: 0.5577 - val_loss: 0.7605
Epoch 47/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7175 - loss: 0.5526 - val_accuracy: 0.6346 - val_loss: 0.6446
Epoch 48/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7032 - loss: 0.5743 - val_accuracy: 0.5641 - val_loss: 0.7304
Epoch 49/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7204 - loss: 0.5617 - val_accuracy: 0.5769 - val_loss: 0.7016
Epoch 50/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7216 - loss: 0.5576 - val_accuracy: 0.6795 - val_loss: 0.6071
Epoch 51/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7280 - loss: 0.5479 - val_accuracy: 0.7051 - val_loss: 0.5845
Epoch 52/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7177 - loss: 0.5540 - val_accuracy: 0.5449 - val_loss: 0.8382
Epoch 53/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7155 - loss: 0.6008 - val_accuracy: 0.6410 - val_loss: 0.7325
Epoch 54/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7059 - loss: 0.5700 - val_accuracy: 0.6731 - val_loss: 0.6086
Epoch 55/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6920 - loss: 0.5687 - val_accuracy: 0.5449 - val_loss: 0.7501
Epoch 56/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7613 - loss: 0.5101 - val_accuracy: 0.6218 - val_loss: 0.6514
Epoch 57/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7507 - loss: 0.5385 - val_accuracy: 0.5577 - val_loss: 0.6923
Epoch 58/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7469 - loss: 0.5438 - val_accuracy: 0.5962 - val_loss: 0.6708
Epoch 59/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7006 - loss: 0.5459 - val_accuracy: 0.5449 - val_loss: 0.8338
Epoch 60/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7257 - loss: 0.5838 - val_accuracy: 0.6987 - val_loss: 0.6095
Epoch 61/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7086 - loss: 0.5637 - val_accuracy: 0.7051 - val_loss: 0.5891
Epoch 62/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7167 - loss: 0.5624 - val_accuracy: 0.5705 - val_loss: 0.7536
Epoch 63/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7462 - loss: 0.5615 - val_accuracy: 0.6667 - val_loss: 0.6795
Epoch 64/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7140 - loss: 0.5612 - val_accuracy: 0.7308 - val_loss: 0.5808
Epoch 65/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7192 - loss: 0.5399 - val_accuracy: 0.6218 - val_loss: 0.6380
Epoch 66/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7277 - loss: 0.5607 - val_accuracy: 0.6859 - val_loss: 0.5795
Epoch 67/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7234 - loss: 0.5502 - val_accuracy: 0.5769 - val_loss: 0.7013
Epoch 68/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7281 - loss: 0.5368 - val_accuracy: 0.6282 - val_loss: 0.6489
Epoch 69/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7552 - loss: 0.5234 - val_accuracy: 0.6667 - val_loss: 0.6289
Epoch 70/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7418 - loss: 0.5293 - val_accuracy: 0.6987 - val_loss: 0.5848
Epoch 71/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7251 - loss: 0.5328 - val_accuracy: 0.6218 - val_loss: 0.6476
Epoch 72/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7427 - loss: 0.5300 - val_accuracy: 0.6667 - val_loss: 0.6124
Epoch 73/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7430 - loss: 0.5652 - val_accuracy: 0.7051 - val_loss: 0.5823
Epoch 74/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7212 - loss: 0.5423 - val_accuracy: 0.5833 - val_loss: 0.7040
Epoch 75/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7598 - loss: 0.5405 - val_accuracy: 0.5513 - val_loss: 0.7835
Epoch 76/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7495 - loss: 0.5351 - val_accuracy: 0.6603 - val_loss: 0.6225
Epoch 77/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7545 - loss: 0.5367 - val_accuracy: 0.5897 - val_loss: 0.6930
Epoch 78/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7576 - loss: 0.5231 - val_accuracy: 0.5577 - val_loss: 0.7231
Epoch 79/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7492 - loss: 0.5346 - val_accuracy: 0.5897 - val_loss: 0.6794
Epoch 80/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7561 - loss: 0.5261 - val_accuracy: 0.5641 - val_loss: 0.7080
Epoch 81/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7518 - loss: 0.5433 - val_accuracy: 0.6795 - val_loss: 0.6106
Epoch 82/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7181 - loss: 0.5537 - val_accuracy: 0.6987 - val_loss: 0.6098
Epoch 83/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7292 - loss: 0.5586 - val_accuracy: 0.7308 - val_loss: 0.5897
Epoch 84/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7522 - loss: 0.5339 - val_accuracy: 0.6538 - val_loss: 0.6122
Epoch 85/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7460 - loss: 0.5426 - val_accuracy: 0.7115 - val_loss: 0.5905
Epoch 86/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7465 - loss: 0.5248 - val_accuracy: 0.6731 - val_loss: 0.6171
Epoch 87/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7675 - loss: 0.5184 - val_accuracy: 0.7372 - val_loss: 0.5864
Epoch 88/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7653 - loss: 0.5159 - val_accuracy: 0.6154 - val_loss: 0.6554
Epoch 89/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7270 - loss: 0.5412 - val_accuracy: 0.6795 - val_loss: 0.6060
Epoch 90/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7416 - loss: 0.5211 - val_accuracy: 0.5962 - val_loss: 0.6762
Epoch 91/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7375 - loss: 0.5261 - val_accuracy: 0.7051 - val_loss: 0.5811
Epoch 92/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7598 - loss: 0.5245 - val_accuracy: 0.6346 - val_loss: 0.6398
Epoch 93/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7406 - loss: 0.5435 - val_accuracy: 0.6667 - val_loss: 0.6029
Epoch 94/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7451 - loss: 0.5192 - val_accuracy: 0.6603 - val_loss: 0.6264
Epoch 95/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7441 - loss: 0.4969 - val_accuracy: 0.5769 - val_loss: 0.7005
Epoch 96/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7561 - loss: 0.5094 - val_accuracy: 0.6603 - val_loss: 0.6117
Epoch 97/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7394 - loss: 0.4925 - val_accuracy: 0.6218 - val_loss: 0.6613
Epoch 98/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7665 - loss: 0.5173 - val_accuracy: 0.6346 - val_loss: 0.6624
Epoch 99/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7550 - loss: 0.5220 - val_accuracy: 0.6603 - val_loss: 0.6571
Epoch 100/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7568 - loss: 0.5255 - val_accuracy: 0.5897 - val_loss: 0.7145
Test accuracy: 0.6051282286643982
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step

,Durchlauf,Modell,Accuracy,F1 Score
0,Baseline,Neuronales Netz 2-Schichten 50 Epochen batchsize 10,0.507692,0.625000
1,Baseline,Neuronales Netz 2-Schichten 50 Epochen batchsize 10,0.446154,0.600000
2,"Baseline 50-Epo, 10-BatchS",Neuronales Netz 2-Layers,0.697436,0.628931
3,"Baseline 50-Epo, 10-BatchS",Neuronales Netz 3-Layers,0.569231,0.142857
4,"Best Seed Opt. 50-Epo, 10-BatchS",Neuronales Netz 3-Layers,0.671795,0.457627
5,"Best Seed Opt. 100-Epo, 50-BatchS",Neuronales Netz 3-Layers,0.738462,0.675159
6,"Best Seed Opt. 100-Epo, 50-BatchS",Neuronales Netz 3-Layers,0.584615,0.198020
7,"Best Seed Opt. 50-Epo, 10-BatchS",Neuronales Netz 3-Layers,0.743590,0.691358
8,"Best Seed Opt. 100-Epo, 50-BatchS",Neuronales Netz 3-Layers,0.738462,0.675159
9,"Best Seed Opt. 100-Epo, 50-BatchS",Neuronales Netz 4-Layers,0.569231,0.066667
10,One-Hot Cat,Neuronales Netz 4-Schichten 50 Epochen batchsize 10,0.758974,0.661871
11,One-Hot Cat,Neuronales Netz 4-Schichten 50 Epochen batchsize 10,0.764103,0.729412
12,Dropout,Neuronales Netz 4-Schichten 2Dropout 100 Epochen batchsize 50,0.558974,0.000000
13,Dropout 0.2,Neuronales Netz 4-Schichten 2Dropout 100 Epochen batchsize 50,0.625641,0.365217
14,Dropout 0.2,Neuronales Netz 4-Schichten 2Dropout 100 Epochen batchsize 50,0.635897,0.323810
15,Dropout 0.2,Neuronales Netz 4-Schichten 2Dropout 100 Epochen batchsize 50,0.574359,0.067416
16,"Dropout 0.2, seed 2856",Neuronales Netz 4-Schichten 2Dropout 100 Epochen batchsize 50,0.605128,0.222222

In [ ]:
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization, Input
categorical_cols = ["Sex", "Ctry", "Town", "Goal of Training",
                    "Preferred Training Daytime", "Subscription Type", "Synchronisation"]

df = df_training_all_features.drop(columns=categorical_cols)  # Ersetze dies mit deiner Datei

#df = df.drop(columns=categorical_cols)
target_column = "User of latest model"
X = df.drop(columns=[target_column])
y = df[target_column]

# Aufteilung in Trainings- und Testdaten
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Baseline-Modellierung
def create_model(seeds, layers, neurons, dropout_rate=0.0, batch_norm=False):
    model = Sequential()
    model.add(Input(shape=(X_train.shape[1],)))
    for _ in range(layers):
        model.add(Dense(neurons, activation='relu',kernel_initializer=tf.keras.initializers.GlorotUniform(seed=seeds)))
        if batch_norm:
            model.add(BatchNormalization())
        if dropout_rate > 0:
            model.add(Dropout(dropout_rate))
    model.add(Dense(1, activation='sigmoid'))
    return model


# Experimentiere mit verschiedenen Parametern
exp = []
seeds = np.random.randint(1, 100, size=10).tolist()
layers = [2, 3, 4]
neurons = [32, 64, 128]
dropout_rates = [0.0, 0.2, 0.5]
batch_norm_options = [True, False]

for seed in seeds:
    np.random.seed(seed)
    tf.random.set_seed(seed)
    for layer in layers:
        for neuron in neurons:
            for dropout_rate in dropout_rates:
                for batch_norm in batch_norm_options:
                    model = create_model(seeds, layer, neuron, dropout_rate, batch_norm)
                    model.compile(optimizer=Adam(), loss='binary_crossentropy', metrics=['accuracy'])
                    model.fit(X_train, y_train, epochs=100, batch_size=50, validation_split=0.2, verbose=0)
                    loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
                    exp.append({
                        "Seed": seed,
                        "Layers": layer,
                        "Neurons": neuron,
                        "Dropout Rate": dropout_rate,
                        "Batch Normalization": batch_norm,
                        "Test Accuracy": accuracy
                    })

# Ergebnisse in einem DataFrame ausgeben
exp_df = pd.DataFrame(exp)
exp_df

KeyboardInterrupt:

In [ ]:
# Ergebnisse in einem DataFrame ausgeben
exp_df = pd.DataFrame(exp)
exp_df

    Seed  Layers  Neurons  Dropout Rate  Batch Normalization  Test Accuracy
0   2856       2       32           0.0                 True       0.630769
1   2856       2       32           0.0                False       0.692308
2   2856       2       32           0.2                 True       0.748718
3   2856       2       32           0.2                False       0.558974
4   2856       2       32           0.5                 True       0.610256
..   ...     ...      ...           ...                  ...            ...
56  2815       2       32           0.2                 True       0.712821
57  2815       2       32           0.2                False       0.558974
58  2815       2       32           0.5                 True       0.682051
59  2815       2       32           0.5                False       0.558974
60  2815       2       64           0.0                 True       0.656410

[61 rows x 6 columns]

from matplotlib import pyplot as plt
exp_df['Seed'].plot(kind='hist', bins=20, title='Seed')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
exp_df['Layers'].plot(kind='hist', bins=20, title='Layers')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
exp_df['Neurons'].plot(kind='hist', bins=20, title='Neurons')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
exp_df['Dropout Rate'].plot(kind='hist', bins=20, title='Dropout Rate')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
exp_df.groupby('Batch Normalization').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
exp_df.plot(kind='scatter', x='Seed', y='Layers', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
exp_df.plot(kind='scatter', x='Layers', y='Neurons', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
exp_df.plot(kind='scatter', x='Neurons', y='Dropout Rate', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
exp_df.plot(kind='scatter', x='Dropout Rate', y='Test Accuracy', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
exp_df['Seed'].plot(kind='line', figsize=(8, 4), title='Seed')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
exp_df['Layers'].plot(kind='line', figsize=(8, 4), title='Layers')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
exp_df['Neurons'].plot(kind='line', figsize=(8, 4), title='Neurons')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
exp_df['Dropout Rate'].plot(kind='line', figsize=(8, 4), title='Dropout Rate')
plt.gca().spines[['top', 'right']].set_visible(False)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(exp_df['Batch Normalization'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(exp_df, x='Seed', y='Batch Normalization', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(exp_df['Batch Normalization'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(exp_df, x='Layers', y='Batch Normalization', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(exp_df['Batch Normalization'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(exp_df, x='Neurons', y='Batch Normalization', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning:

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(exp_df['Batch Normalization'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(exp_df, x='Dropout Rate', y='Batch Normalization', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [15]:
from tensorflow.keras.callbacks import Callback
from tensorflow.keras.callbacks import EarlyStopping
# Benutzerdefinierter Callback, um das Training zu stoppen, wenn die Accuracy in der ersten Epoche niedriger als 0.62 ist
class StopTrainingCallback(Callback):
    def on_epoch_end(self, epoch, logs=None):
        if epoch == 0 and logs.get('accuracy') < 0.62:
            self.model.stop_training = True
            print("Stopping training due to low initial accuracy.")

early_stopping = EarlyStopping(
    monitor='val_loss',  # Überwache den Verlust auf der Validierungsmenge
    patience=10,         # Warte 10 Epochen, bevor das Training gestoppt wird
    restore_best_weights=True  # Wiederherstellung der besten Gewichte
)